---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unifi-mcp
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: unifi-mcp-secret
    template:
      data:
        UNIFI_NETWORK_API_KEY: "{{ .apiKey }}"
        UNIFI_NETWORK_PASSWORD: "{{ .password }}"
        UNIFI_NETWORK_USERNAME: "{{ .username }}"
  data:
    - secretKey: apiKey
      remoteRef:
        key: unifi-mcp
        property: API_KEY
    - secretKey: password
      remoteRef:
        key: unifi-mcp
        property: PASSWORD
    - secretKey: username
      remoteRef:
        key: unifi-mcp
        property: USERNAME
