---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system
resources:
  - ./add-volsync-resource.yaml
  - ./apply-ingress-auth-annotations.yaml
  - ./apply-ingress-whitelist-annotations-internal.yaml
  - ./remove-container-cpu-limit.yaml
  - ./validated-ingress-external-target.yaml
