---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  labels:
    app.kubernetes.io/name: homepage
data:
  bookmarks.yaml: |
    - Communicate:
        - Gmail:
            - icon: gmail.png
              href: 'https://mail.google.com/mail/u/3/#inbox'
        - Google Calendar:
            - icon: google-calendar.png
              href: 'https://calendar.google.com/calendar/u/3/r'
    - Media:
        - YouTube:
            - icon: youtube.png
              href: 'https://youtube.com/feed/subscriptions'
        - Youtube Music:
            - icon: https://raw.githubusercontent.com/homarr-labs/dashboard-icons/refs/heads/main/png/youtube-music.png
              href: 'https://music.youtube.com'
    - Git:
        - kubesearch:
            - icon: kubernetes-dashboard.png
              href: 'https://kubesearch.dev/'
        - home-ops:
            - icon: github.png
              href: 'https://github.com/aumer-amr/labv2'
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
  services.yaml: ""
  settings.yaml: |
    title: Dashboard
    favicon: https://github.com/homarr-labs/dashboard-icons/blob/main/png/clash.png
    useEqualHeights: true
    theme: dark
    color: slate
    headerStyle: clean
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: true
      showSearchSuggestions: true
      hideVisitURL: true
    layout:
      Network:
        style: row
        columns: 3
        icon: mdi-network
      Games:
        style: row
        columns: 3
        icon: mdi-minecraft
      Calendar:
        style: column
        icon: mdi-calendar
      Video:
        style: column
        icon: mdi-play-circle
      Books:
        style: row
        columns: 2
        icon: mdi-book
      Infrastructure:
        style: row
        columns: 5
        icon: mdi-server
      Observability:
        style: row
        columns: 5
        icon: mdi-chart-line
      Home:
        style: row
        columns: 5
        icon: mdi-home-analytics
      Downloads:
        style: row
        columns: 3
        icon: mdi-download-circle
  widgets.yaml: |
    - logo:
        icon: https://raw.githubusercontent.com/aumer-amr/labv2/refs/heads/main/raw/amr.png
    - search:
        provider: [google]
        focus: false
        target: _blank
    - greeting:
        text_size: xl
        text: "Howdy Hey!"
    - kubernetes:
        cluster:
          cpu: true
          memory: true
          show: true
          showLabel: true
        nodes:
          cpu: true
          memory: true
          show: false
          showLabel: true
    - openmeteo:
        label: Home
        latitude: ${LATITUDE}
        longitude: ${LONGITUDE}
        units: metric
        cache: 5
    - datetime:
        text_size: l
        format:
          timeStyle: short
          dateStyle: short
          hourCycle: h23
