---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

components:
  - ../../components/sops
  - ../../components/kopiur/secret

resources:
  - ./namespace.yaml
  - ./network-policies/ks.yaml
  - ./cilium/ks.yaml
  - ./hubble-auth/ks.yaml
  - ./coredns/ks.yaml
  - ./descheduler/ks.yaml
  - ./drm-exporter/ks.yaml
  - ./gvisor/ks.yaml
  - ./ocharted/ks.yaml
  - ./metrics-server/ks.yaml
  - ./reloader/ks.yaml
  - ./spegel/ks.yaml
  - ./snapshot-controller/ks.yaml
  - ./kopiur/ks.yaml
  - ./intel-gpu-resource-driver/ks.yaml
