---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-qbittorrent-exporter
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: qbittorrent
      namespace: downloads
  values:
    controller:
      type: daemonset
      replicas: 1
    image:
      repository: ghcr.io/k8s-at-home/prometheus-qbittorrent-exporter
      tag: v1.2.0
    env:
      QBITTORRENT_HOST: qbittorrent.downloads.svc.cluster.local
      QBITTORRENT_PORT: "8080"
      VERIFY_WEBUI_CERTIFICATE: "false"
    service:
      main:
        ports:
          http:
            port: 8000
    serviceMonitor:
      main:
        enabled: false
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
            relabelings:
              - sourceLabels: [__meta_kubernetes_pod_node_name]
                targetLabel: node
    securityContext:
      privileged: true
