---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-postgres
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: ${APP}-postgres
    template:
      type: kubernetes.io/basic-auth
      data:
        dbname: ${APP}
        host: ${APP}-rw.${NAMESPACE}.svc.cluster.local
        username: ${APP}
        password: "{{ .POSTGRES_PASSWORD }}"
        port: "5432"
        sslmode: ${PG_SSLMODE:=verify-full}
  dataFrom:
    - extract:
        key: ${APP}
