---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-backup
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: ${APP}-backup
    template:
      data:
        ACCESS_KEY_ID: "{{ .R2_ACCESS_KEY_ID }}"
        ACCESS_SECRET_KEY: "{{ .R2_SECRET_ACCESS_KEY }}"
        REGION: auto
  dataFrom:
    - extract:
        key: ${APP}
