---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: ${APP}-postgres
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: ${APP}
  podMetricsEndpoints:
    - port: metrics
