---
apiVersion: gatus.io/v1alpha1
kind: Gatus
metadata:
  name: &name rook
  namespace: rook-ceph
spec:
  endpoint:
    name: *name
    group: guarded
    ui:
      hide-url: true
      hide-hostname: true
    url: https://rook.${SECRET_DOMAIN}
    interval: 1m
