---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitwarden-backup-pvc
  namespace: kube-system
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: nas-vault-backup
  resources:
    requests:
      storage: 1Mi
