apiVersion: v1
kind: Secret
metadata:
    name: bitwarden-cli
    namespace: kube-system
stringData:
    BW_CLIENTID: ENC[AES256_GCM,data:goDqIpdul1ANAsLpOL/4JPF3aWlXOI96pWia0h9BjGNsxZFQZHXSMU0=,iv:s4fMNPhM06oZ2Ko8+F99MiG6i6UsL/3d+dUmd4b0g/8=,tag:6EG6giiaVquObrEHUUeRyA==,type:str]
    BW_CLIENTSECRET: ENC[AES256_GCM,data:yuW0MgHrwGOu2j5y2F7uTqyD4Lje6ebL2GvMc/QZ,iv:3Vvuhx5ANWw1YC/Hs+/MmRyOBRoGP8H6eXhSPzR0Jyo=,tag:Tp8DjABi27lrL2/dETadXg==,type:str]
    BW_HOST: ENC[AES256_GCM,data:qUfmzksBo8ILr6Bp2754RbSYU8M=,iv:iIw6JbCm5nie2RnQPMoVb+RYInBYII8XtrWs+chyXUo=,tag:mtX0tU33hfSrIb5FdBatSw==,type:str]
    BW_PASSWORD: ENC[AES256_GCM,data:nMCpFZA5HR8akUn40UhukK/Y,iv:piDmzSmDEvuFNLd4gvYpfV5WkdN1lwC7dJEtbBmKoVQ=,tag:F3Ly2AQ+2M7kTiSFC3vq4A==,type:str]
    VC_PASSWORD: ENC[AES256_GCM,data:4/qLqEmjh4elzE9cZEhRrY1bokE8Bpoev8avHhnMQsks3REAc3DmsQ==,iv:KF6aPH872womuxWnkGpwMd7jNsZ5EvgDRLEw3ty12dc=,tag:DgAVXXVHdW/zlCu6PIIk5g==,type:str]
    DEBUG: ENC[AES256_GCM,data:J2ntIg==,iv:azPVLsshkDJXuEb04Z2JonWb2P7o0bz1WbhslH8CQr0=,tag:AxQUcEP8r1CowiVOHSuRYg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x05r8tdwj7ruzqffcuamt3v7gnf82ldcmrjq8zd3fnh9593grd8sktr4ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQeG1jWU4zUGUrWERkWkZG
            cDdzL0ZaVDhZTXc4VjVQaUdOcGJpdzhqNGtzCldUOWcxcFkreHN0VHg0aXdSbDgv
            RkFHMDU2YnpjOXNobWxPbnJSaVAvbncKLS0tIDlKUlpBV0tvU3ZYck9FR0c5dXF3
            Y0libG92ZVl3ZUZ1WHJlTFBYNGNYN1EK5MNZEdUR7W5adlvSqRqEngksm/H4l1se
            /pzc3dgcRYKY2smZqrYJ+Nw9zKOIeNMs8lChrjgW89d0VzHRElRdjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-21T23:42:54Z"
    mac: ENC[AES256_GCM,data:OWNsDCTuUOuCWY7qssoIS4KMt4vQZpc2Qk9MllmFD5t4RQwBihA15ZjRYcDiYvnJk/0zKVgl4kx3VglhZd5bGkSOuDLicN/bf4bzefwZsYz9vh5x5pH742CVXkOZfbRPCwFJKO6d6tHqdL4JIDXJQSZCT/1sVnhZ2UaeI190ANQ=,iv:iEvEMrQrIjukV6Hybegz4A5M80VDnFVnfjWzm5sPdiY=,tag:IyAdeBIriFBIJNCJE0zbiw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
