---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: pokemon
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/aumer-amr/pokemon
      tag: sha-de96708
    service:
      main:
        ports:
          http:
            port: 5000
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: true
      startup:
        enabled: false
    ingress:
      main:
        enabled: true
        ingressClassName: external-public
        annotations:
          hajimari.io/enable: "false"
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_PUBLIC_DOMAIN}"
          policy-control.aumer.io/gatus-generate: "true"
          policy-control.aumer.io/gatus-dns: "true"
          policy-control.aumer.io/gatus-conditions: "[STATUS] == 200"
          policy-control.aumer.io/gatus-path: "/"
        hosts:
          - host: &host "pokemon.${SECRET_PUBLIC_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host
    resources:
      requests:
        cpu: 10m
        memory: 128M
    volumeClaimTemplates:
      - name: data
        mountPath: /data
        accessMode: ReadWriteOnce
        size: 100Mi
        storageClass: longhorn-config
