---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./netpol.yaml
  - ./helmrelease.yaml
labels:
  - pairs:
      app.kubernetes.io/name: netpol
      app.kubernetes.io/instance: netpol
