---
originRequest:
  http2Origin: true

# https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/ingress
ingress:
  - hostname: "${SECRET_PUBLIC_DOMAIN}"
    service: https://nginx-external-public-controller.networking.svc.cluster.local:443
    originRequest:
      originServerName: "external.${SECRET_PUBLIC_DOMAIN}"
  - hostname: "*.${SECRET_PUBLIC_DOMAIN}"
    service: https://nginx-external-public-controller.networking.svc.cluster.local:443
    originRequest:
      originServerName: "external.${SECRET_PUBLIC_DOMAIN}"
  - service: http_status:404
