---
originRequest:
  http2Origin: true

# https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/ingress
ingress:
  - hostname: "${SECRET_PUBLIC_DOMAIN}"
    service: https://kromgo.${SECRET_PUBLIC_DOMAIN}
    originRequest:
      originServerName: "external.${SECRET_PUBLIC_DOMAIN}"
  - service: http_status:404
