---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: downloads
resources:
  - ./helmrelease.yaml
  - ./qbittools-tagging
labels:
  - pairs:
      app.kubernetes.io/name: qbittorrent
      app.kubernetes.io/instance: qbittorrent
configMapGenerator:
  - name: qbittorrent-dashboard
    files:
      - qbittorrent-dashboard.json=https://raw.githubusercontent.com/esanchezm/prometheus-qbittorrent-exporter/master/grafana/dashboard.json
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
  labels:
    grafana_dashboard: "true"
