---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: downloads
resources:
  - ./pvc.yaml
  - ./helmrelease.yaml
  - ./qbittools-tagging
labels:
  - pairs:
      app.kubernetes.io/name: qbittorrent
      app.kubernetes.io/instance: qbittorrent
