apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-downloads
  namespace: downloads
spec:
  storageClassName: nas-media
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
