---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  chartRef:
    kind: OCIRepository
    name: kube-prometheus-stack
  interval: 1h
  valuesFrom:
    - kind: ConfigMap
      name: flux-metrics-configmap
      valuesKey: flux-metrics.yaml
  values:
    cleanPrometheusOperatorObjectNames: true
    alertmanager:
      route:
        main:
          enabled: true
          matches:
            - path:
                type: Exact
                value: /-/healthy
          additionalRules:
            - name: ui
              matches:
                - path:
                    type: PathPrefix
                    value: /
              backendRefs:
                - name: kube-prometheus-stack-alertmanager
                  port: 9093
          hostnames:
            - alertmanager.${SECRET_DOMAIN}
          parentRefs:
            - name: envoy-internal
              namespace: network
      alertmanagerSpec:
        podMetadata:
          labels:
            network.home.arpa/from-envoy-internal: allow
        alertmanagerConfiguration:
          name: alertmanager
        externalUrl: https://${SECRET_DOMAIN}
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: ceph-block
              resources:
                requests:
                  storage: 1Gi
    kubeEtcd:
      service:
        selector:
          component: kube-apiserver # etcd runs on control plane nodes
    kubeProxy:
      enabled: false
    prometheus:
      route:
        main:
          enabled: true
          annotations:
            gatus.home-operations.com/endpoint: |-
              path: /-/healthy
              conditions: ["[STATUS] == 200"]
          matches:
            - path:
                type: Exact
                value: /-/healthy
          additionalRules:
            - name: ui
              matches:
                - path:
                    type: PathPrefix
                    value: /
              backendRefs:
                - name: kube-prometheus-stack-prometheus
                  port: 9090
          hostnames:
            - prometheus.${SECRET_DOMAIN}
          parentRefs:
            - name: envoy-internal
              namespace: network
      prometheusSpec:
        podMetadata:
          labels:
            network.home.arpa/from-envoy-internal: allow
        externalUrl: https://prometheus.${SECRET_DOMAIN}
        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        ruleSelectorNilUsesHelmValues: false
        scrapeConfigSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        retention: 30d
        retentionSize: 40GiB
        resources:
          requests:
            cpu: 100m
          limits:
            memory: 4Gi
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: ceph-block
              resources:
                requests:
                  storage: 50Gi
    prometheus-node-exporter:
      fullnameOverride: node-exporter
    kube-state-metrics:
      fullnameOverride: kube-state-metrics
    grafana:
      enabled: false
      forceDeployDashboards: true
      operator:
        dashboardsConfigMapRefEnabled: true
        folder: observability
        matchLabels:
          dashboards: grafana
