---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-gateway
spec:
  chartRef:
    kind: OCIRepository
    name: k8s-gateway
  interval: 1h
  values:
    customLabels:
      platform.home.arpa/tier: "0"
    fullnameOverride: k8s-gateway
    domain: "${SECRET_DOMAIN}"
    ttl: 1
    service:
      type: LoadBalancer
      port: 53
      annotations:
        lbipam.cilium.io/ips: "10.10.1.112"
      externalTrafficPolicy: Cluster
    watchedResources: ["HTTPRoute", "Service"]
    replicaCount: 2
    topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/instance: k8s-gateway
            app.kubernetes.io/name: k8s-gateway
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
