---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-gateway
spec:
  chartRef:
    kind: OCIRepository
    name: k8s-gateway
  interval: 1h
  values:
    customLabels:
      platform.home.arpa/tier: "0"
    fullnameOverride: k8s-gateway
    servers:
      - zones:
          - zone: .
            use_tcp: true
        port: 1053
        servicePort: 53
        plugins:
          - name: k8s_gateway
            parameters: "${SECRET_DOMAIN}"
            configBlock: |-
              apex k8s-gateway.network
              ttl 1
              resources HTTPRoute Service
          - name: log
          - name: errors
          - name: health
            configBlock: |-
              lameduck 5s
          - name: ready
          - name: prometheus
            parameters: 0.0.0.0:9153
          - name: forward
            parameters: . /etc/resolv.conf
          - name: loop
          - name: reload
          - name: loadbalance
    serviceType: LoadBalancer
    service:
      annotations:
        lbipam.cilium.io/ips: "10.10.1.112"
        prometheus.io/port: "9153"
        prometheus.io/scrape: "true"
      externalTrafficPolicy: Cluster
    deployment:
      dnsPolicy: ClusterFirst
    securityContext:
      runAsUser: 1000
    resources:
      limits: null
      requests: null
    readinessProbe:
      initialDelaySeconds: 10
      periodSeconds: 10
      failureThreshold: 5
    replicaCount: 2
    topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/instance: k8s-gateway
            app.kubernetes.io/name: k8s-gateway
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
