---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: plane-external-secret #redeploy
  namespace: home
spec:
  target:
    name: plane-secret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        DEBUG: "0"
        SENTRY_DSN: ""
        DJANGO_SETTINGS_MODULE: plane.settings.production
        DATABASE_URL: postgresql://{{ .plane_pg_user }}:{{ .plane_pg_pass }}@postgres-rw.database.svc.cluster.local/plane
        REDIS_URL: redis://redis.database.svc.cluster.local:6379
        EMAIL_HOST: smtp.gmail.com
        EMAIL_PORT: "587"
        EMAIL_HOST_USER: "{{ .plane_smtp_username }}"
        EMAIL_HOST_PASSWORD: "{{ .plane_smtp_password }}"
        EMAIL_FROM: "{{ .plane_smtp_email_from }}"
        EMAIL_USE_TLS: "0"
        EMAIL_USE_SSL: "0"
        AWS_REGION: "WEUR"
        AWS_ACCESS_KEY_ID: "{{ .aws_access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ .aws_secret_access_key }}"
        AWS_S3_BUCKET_NAME: "plane"
        AWS_S3_ENDPOINT_URL: "https://${SECRET_CLOUDFLARE_ACCOUNT_ID}.r2.cloudflarestorage.com"
        FILE_SIZE_LIMIT: "5242880"
        WEB_URL: "https://plane.${SECRET_DOMAIN}"
        DISABLE_COLLECTSTATIC: "1"
        DOCKERIZED: "1"
        SECRET_KEY: "{{ .plane_secret_key }}"
        DEFAULT_EMAIL: "{{ .plane_default_email }}"
        DEFAULT_PASSWORD: "{{ .plane_default_password }}"
        USE_MINIO: "0"
        ENABLE_SIGNUP: "0"
        # Postgres Init
        INIT_POSTGRES_DBNAME: |-
          plane
        INIT_POSTGRES_HOST: |-
          postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: |-
          {{ .plane_pg_user }}
        INIT_POSTGRES_PASS: |-
          {{ .plane_pg_pass }}
        INIT_POSTGRES_SUPER_USER: |-
          {{ .pg_super_user }}
        INIT_POSTGRES_SUPER_PASS: |-
          {{ .pg_super_pass }}
  data:
    - secretKey: pg_super_user
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b0f64f2d-7a43-4ac2-9b6d-b02e01525324
        property: username
    - secretKey: pg_super_pass
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b0f64f2d-7a43-4ac2-9b6d-b02e01525324
        property: password
    - secretKey: plane_pg_user
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: b0f64f2d-7a43-4ac2-9b6d-b02e01525324
        property: plane_pg_user
    - secretKey: plane_pg_pass
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: b0f64f2d-7a43-4ac2-9b6d-b02e01525324
        property: plane_pg_pass
    - secretKey: plane_smtp_username
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 7f7a2a4c-ad36-49bf-8abd-b061009ec47e
        property: plane_smtp_username
    - secretKey: plane_smtp_password
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 7f7a2a4c-ad36-49bf-8abd-b061009ec47e
        property: plane_smtp_password
    - secretKey: aws_access_key_id
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 7f7a2a4c-ad36-49bf-8abd-b061009ec47e
        property: aws_access_key_id
    - secretKey: aws_secret_access_key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 7f7a2a4c-ad36-49bf-8abd-b061009ec47e
        property: aws_secret_access_key
    - secretKey: plane_secret_key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 7f7a2a4c-ad36-49bf-8abd-b061009ec47e
        property: plane_secret_key
    - secretKey: plane_default_email
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 7f7a2a4c-ad36-49bf-8abd-b061009ec47e
        property: username
    - secretKey: plane_default_password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 7f7a2a4c-ad36-49bf-8abd-b061009ec47e
        property: password

