---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    key_groups:
      - age:
          - "age17hf2h7uc36snm6hta9l93duhyx6h4q7q8lt9fa89uu67jnajrpts24v5w2"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    key_groups:
      - age:
          - "age17hf2h7uc36snm6hta9l93duhyx6h4q7q8lt9fa89uu67jnajrpts24v5w2"
stores:
  yaml:
    indent: 2
