---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shlink-gatus
  namespace: default
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: Links
        group: tools
        url: https://sh.${SECRET_DOMAIN}/jb6d5
        interval: 1m
        conditions: ["[STATUS] == 302"]
        alerts: [{ type: discord }]
        ui:
          hide-hostname: true
          hide-url: true
