---
alertmanager:
  interval: 60s
  servers:
    - name: home
      uri: http://kube-prometheus-stack-alertmanager.monitoring.svc.cluster.local:9093
      timeout: 10s
      healthcheck:
        visible: false
        filters:
          alertmanager:
            - alertname=Watchdog
            - prometheus=monitoring/kube-prometheus-stack
