---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: home-assistant-external-secret
  namespace: home
spec:
  target:
    name: home-assistant-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        # App
        HASS_POSTGRES_URL: |-
          postgresql://{{ .hass_pg_user }}:{{ .hass_pg_pass }}@postgres-rw.database.svc.cluster.local/home_assistant
        # Postgres Init
        INIT_POSTGRES_DBNAME: |-
          home_assistant
        INIT_POSTGRES_HOST: |-
          postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: |-
          {{ .hass_pg_user }}
        INIT_POSTGRES_PASS: |-
          {{ .hass_pg_pass }}
        INIT_POSTGRES_SUPER_USER: |-
          {{ .pg_super_user }}
        INIT_POSTGRES_SUPER_PASS: |-
          {{ .pg_super_pass }}
  data:
    - secretKey: pg_super_user
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b0f64f2d-7a43-4ac2-9b6d-b02e01525324
        property: username
    - secretKey: pg_super_pass
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b0f64f2d-7a43-4ac2-9b6d-b02e01525324
        property: password
    - secretKey: hass_pg_user
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: b0f64f2d-7a43-4ac2-9b6d-b02e01525324
        property: hass_pg_user
    - secretKey: hass_pg_pass
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: b0f64f2d-7a43-4ac2-9b6d-b02e01525324
        property: hass_pg_pass
