---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-tetragon
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-cilium
  path: ./kubernetes/apps/kube-system/tetragon/app
  prune: false # never should be deleted
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-tetragon-policies
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-cilium
  path: ./kubernetes/apps/kube-system/tetragon/policies
  prune: false # never should be deleted
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m

