apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authelia
  namespace: system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
