---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: satisfactory-external-secret
  namespace: default
spec:
  target:
    name: satisfactory-secret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        DISCORD_INFO_CHANNEL_ID: "{{ .DISCORD_INFO_CHANNEL_ID }}"
        DISCORD_MESSAGE_CHANNEL_ID: "{{ .DISCORD_MESSAGE_CHANNEL_ID }}"
        DISCORD_TOKEN: "{{ .DISCORD_TOKEN }}"
        DISCORD_HEALTH_MESSAGE_ID: "{{ .DISCORD_HEALTH_MESSAGE_ID }}"
        DISCORD_PROGRESS_MESSAGE_ID: "{{ .DISCORD_PROGRESS_MESSAGE_ID }}"
        DISCORD_GAME_MESSAGE_ID: "{{ .DISCORD_GAME_MESSAGE_ID }}"
        CRON_SCHEDULE: "{{ .CRON_SCHEDULE }}"
        SATISFACTORY_API_TOKEN: "{{ .SATISFACTORY_API_TOKEN }}"
        SATISFACTORY_API_URL: "{{ .SATISFACTORY_API_URL }}"
  data:
    - secretKey: DISCORD_INFO_CHANNEL_ID
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 8f04bba0-7ebd-48bf-92c3-b1e90187559c
        property: DISCORD_INFO_CHANNEL_ID
    - secretKey: DISCORD_MESSAGE_CHANNEL_ID
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 8f04bba0-7ebd-48bf-92c3-b1e90187559c
        property: DISCORD_MESSAGE_CHANNEL_ID
    - secretKey: DISCORD_TOKEN
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 8f04bba0-7ebd-48bf-92c3-b1e90187559c
        property: DISCORD_TOKEN
    - secretKey: DISCORD_HEALTH_MESSAGE_ID
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 8f04bba0-7ebd-48bf-92c3-b1e90187559c
        property: DISCORD_HEALTH_MESSAGE_ID
    - secretKey: DISCORD_PROGRESS_MESSAGE_ID
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 8f04bba0-7ebd-48bf-92c3-b1e90187559c
        property: DISCORD_PROGRESS_MESSAGE_ID
    - secretKey: DISCORD_GAME_MESSAGE_ID
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 8f04bba0-7ebd-48bf-92c3-b1e90187559c
        property: DISCORD_GAME_MESSAGE_ID
    - secretKey: CRON_SCHEDULE
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 8f04bba0-7ebd-48bf-92c3-b1e90187559c
        property: CRON_SCHEDULE
    - secretKey: SATISFACTORY_API_TOKEN
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 8f04bba0-7ebd-48bf-92c3-b1e90187559c
        property: SATISFACTORY_API_TOKEN
    - secretKey: SATISFACTORY_API_URL
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 8f04bba0-7ebd-48bf-92c3-b1e90187559c
        property: SATISFACTORY_API_URL
