---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./external-secret.yaml
  - ./helmrelease.yaml
labels:
  - pairs:
      app.kubernetes.io/name: satisfactory
      app.kubernetes.io/instance: satisfactory
