ansible_become_pass: ENC[AES256_GCM,data:R3DHxnfiHgC7Ew==,iv:5Xm4hKVro5bq8QhLQORqDIwDeljC5GvyAeVeNWa3x/Y=,tag:dAOpXavkX+FGQCjAif/OBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x05r8tdwj7ruzqffcuamt3v7gnf82ldcmrjq8zd3fnh9593grd8sktr4ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVDMzd0xMMS9Vd3RFVGJU
            RGdCbGhod3FUekZmbFE3bkNpTHVBOTR5UHpVCnlpNnB2K0N1K1RIdXhtN2Rtb3JU
            Y003WjhmUldaNE4rbUVCVWxSSktScDQKLS0tIHpNUFpRMXFadTl3ckNsd0tYZ1hh
            U0w2S2ZjMURod3AxSWJuTTlKS1hMUjQKDkMpEarjguB1JAAiXeju5D3kaHUOk2vO
            lg8DyirmvfqfuqLhaE7bSrh/hVspupfsAZ/qXiVLhWk+uqr/A5qphw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-24T09:31:43Z"
    mac: ENC[AES256_GCM,data:hTG7F9Fk0cbp7BVZ/NX3qIX8kja2dQCI8XVGgBOHz0hAQ6YLoqep2Gnaj+wYF47QedoaOOathFC4L7vtEAexq3IIJq/SOx/ITJECw5eQCcZqKYcoocaqm584boKe03LGqPYWPzutqlG4Ao2pgiXNWjQfosRiQJBbRzBGzq2ghkA=,iv:7mu6jJfP0s8n4dj9dpJdCJyDCY0fsJ9YkiT2xD9KV+k=,tag:dajrJD6YW0/ueBVcEoYmxg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
