ansible_become_pass: ENC[AES256_GCM,data:3NDHGHz6/C3mXA==,iv:0lR5j0bz5sIRPNy7tKH4t67w8YW3ip64RqpxiP8gG/Q=,tag:wdL9mBupOfU/Bk0R+95QPw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x05r8tdwj7ruzqffcuamt3v7gnf82ldcmrjq8zd3fnh9593grd8sktr4ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzVmtzYmUrclpZbW1NcVVL
            QkNOTlVucklnM2xkMFhzSGVMcXJ3N0NlTXpZCm1vRVplNjJ0aFpWbFRQM2Qxc05I
            MGJWYm9LQWRUM1NmY1MxbE4wK1BQQ2sKLS0tIGpJR256MEpBZDBNLzB3cXFGSkRn
            L0JIM0tWNm5CK3lCRHVSSjZoTUtMZ2cK3MRh99hU6mKJwge7ze6w3MP8Q6CLJbKl
            64VDFs1qSV/oFHS3j4V/+Dz5+3ji5sm8o+CAwCfHiioD8bKBg1z6sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-18T11:48:49Z"
    mac: ENC[AES256_GCM,data:iEigrGiuQAE7H/1rU1hbPKZH4Pr4ZxoaRaroV+pmXFDKjGPa7H7RfXLk1GV166ifeLXzA9rpQX/NTvMywJ1CalJ7mhJTogG7iLWFDtE1RRHT+I4StffRAxNyG7rFacD3mLVzXhaq9tj75RYxf0vN29fgOBVO62MX36yVQ+MOiAU=,iv:d/6k2FwPKHtn9YlQJhEP5B23k/LRjeKv0ONfA3wXIvI=,tag:g0tOFK1x/gLXLqEjkD4dvg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
