ansible_become_pass: ENC[AES256_GCM,data:CnujBQH7+MM4Wg==,iv:DKngibgwQoW3RKdyFFAyDh0KmkvixtqQPApizsyQdEc=,tag:UGiJAJ3PUEQQiKBCuR9SlA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x05r8tdwj7ruzqffcuamt3v7gnf82ldcmrjq8zd3fnh9593grd8sktr4ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrWUgwa3BwaWpkaFBYaW5i
            NUF2RWFQVVBpZlE0UWFZdFRub0hsNmsrdlJnCllIeHdoVmo5U0Q0d2lkNmowdjc4
            dFEzQWUzUnhXalBOK3dWek9PL0RwUU0KLS0tIE9sNGlkVGU1TnhVU3BNNmsyemdR
            WFAzOGVtaTlvdFRxdE8xWEo1aUNYUkEKsAB5pLJewvi5wbhjIfsSIvCPE1f2tE4F
            00Ltt7013cL+I2GG3VeNvS15E3r/gHdSNPDvkjDUoZFn5YisfiM+Ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-18T11:28:06Z"
    mac: ENC[AES256_GCM,data:UlOOPKHQtac5F8vdRWd0UJ3IAS5virnMKOsXuQr6Sa4T7rV6IfcLloyhaxhC9C/A27BKbsJb5fPAGYmcb2GkhPkRKs6mAT099YdpiXgBJ1vHGU9QmqtSqstw2yNMJAjZam61E3Q8pWDq3LK8sowhPB8VR8Gp+ji3DPJ0Q53Utao=,iv:wOJ0j7CokjTMmNcqzN3wZVxQC0Takzb4j+bagXDpG+4=,tag:CPHgFbw0XaGLlJF/1gsHFg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
