---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-influxdb
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-longhorn
  path: ./kubernetes/apps/database/influxdb/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
