---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
resources:
  - ./allow-egress-kube-apiserver.yaml
  - ./allow-ingress-nginx-external.yaml
  - ./allow-ingress-nginx-internal.yaml
  - ./deny-egress-all.yaml
