---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
resources:
  - ./allow-egress-cloudflare-r2.yaml
  - ./allow-egress-google-smtp.yaml
  - ./allow-egress-kube-apiserver.yaml
  - ./allow-egress-kube-dns.yaml
  - ./allow-egress-mariadb.yaml
  - ./allow-ingress-nginx-external.yaml
  - ./allow-ingress-nginx-internal.yaml
  - ./deny-egress-all.yaml
  - ./monitor-l7-https.yaml
