---
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "l7-visibility"
spec:
  endpointSelector:
    matchLabels:
      monitor.home.arpa/https: enabled
  egress:
    - toPorts:
      - ports:
        - port: "443"
          protocol: ANY
        rules:
          http: [{}]
