---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-mcp
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: paperless-mcp-secret
    template:
      data:
        PAPERLESS_API_KEY: "{{ .apiKey }}"
  data:
    - secretKey: apiKey
      remoteRef:
        key: paperless
        property: PAPERLESS_API_KEY
