# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:DtkO4hWB/R8srLZ3h7+lZeFcjdCf7NmSvypw6n9+oiYPzEk4,iv:NOl2XQX5qGYN4edHmki8aFVcUviMAiqTX8Bx9eW/McI=,tag:qQB/xNWGq3ATu6ZZ0oyhow==,type:str]
  credentials.json: ENC[AES256_GCM,data:3zMriA1gI3rB9FOY7UJTt7p9tWP6UkX2X3fKXBC5vsIQwqNcpWzoGLnaDV2N0OUbUF9SFix6Sj1tMVVaiGf6dpAcq6UUXPRYsOp4MQtSRWrMnQ319xkuveMv6Pz/jc4xExfOG1is6RdgKqSTjliHQ0dENMNWZkx6uiR0AbTBhm8al24PzpVao8EVrQ6sl/FTCIZDSLUFtiIvoIiYg0qAELDM04PuYRZpbHJG+J3H4w==,iv:VdfNcG/SNh3ThjkOyxU49Abwn1zRvZvUi0xG1TedWzs=,tag:RObwq2ZiYRgo8+7yCLHn5A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age17hf2h7uc36snm6hta9l93duhyx6h4q7q8lt9fa89uu67jnajrpts24v5w2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBadFlEcE93L0U1L1ZBa3dj
        OXJOZkdZR0dhWGYzd0dORWxqK1hWTUFQRTE0ClNqUmJHY1QyVVJveFhHS0QySzJS
        dkNtY0NRY2dwNFZOaDY3SG1mcG9aM00KLS0tIHFobUY0RGxFTjYvekNNS092RDcr
        ZGZhNDhSenBQYmtGSnF1bG11dzJIbjQKyQ+Z3anRq9rw6b62qlnkJeXUBRedxXB9
        mmo6SKMd9xDWQRwEFoZlwclQX9Q1xf/gMqrAIeYRTix8LxLHngR1dg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-11T20:03:20Z"
  mac: ENC[AES256_GCM,data:yGbDCeNNMXgikh27AcgjJMfbHB82Ecjpl3uoFLxcQc7SbSVq9kkOPbbuGLFoOa1kp47MvPqYzL8g5vDhoTKeRkpupC/Xp3RW574V3M2hbsQk0YM6Mag+m6HMdxFUKJUbjsnVQizh714rJNUQN3pP8w2dtlz4RwfFuKpM17vrE80=,iv:621TPfZKNNr3yQdRtkBAdanJSjsqECdlZGe5KjCE58E=,tag:CA8VenObnCfVmIjquHODLw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
