# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:c+ZzWWrzrDN5zsu0K2vgBCqeKr2Q9CrWuCv6s19I3G2AwjVg,iv:UVpx0BGfL2ifUTqF7JVDspr/ixvP16ttDF7cWXZu6HY=,tag:Go2zguky/W7vmzdLukcHeg==,type:str]
  credentials.json: ENC[AES256_GCM,data:W/1gaFKryfRFd53Yy6lOMorQM1bZDDdOSvYBIm/FG/QbJzlVbetbNE+xJ3mcZFj3XYFC9KjgCjNCcoH71j+L7aIs51eEAYz1lX7Hlu6DpZBYvKj2wAiXN4v7kTYFTq78Am1HQ8SqAeb7Qop7kMToetsfu76RYn82KG0hq0UUBpabBwVmGpa86Y2cunN0YKTfmRy0qU3GjSngrVlvaC0gIwKZBzJhv3P2qt47bKAoZw==,iv:TzJ+zY28REoZeKgTiWW+S45YW5hr9XRMvCJrnL1qTS0=,tag:d/mjHfUK+4REocFXZuFQag==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age17hf2h7uc36snm6hta9l93duhyx6h4q7q8lt9fa89uu67jnajrpts24v5w2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQVVuU0RNMm9MblJhK2hw
        SWJWMUhHTmVHZEZBSFRxUDFBdm1MSVM5d2xRClVkS3Y4TC8yRlpvOUNsYkplSElD
        MzZtMFBxbmRHcXFZYzVDYUdJeGFHM3cKLS0tIHd0cjZJMitxNjk1ZExvYllBNVd4
        ZDZVMkZKbkJmZy9QbTVHY1ZWMXMzMVkK+PpEnXHNimsolMSEzsaS1xAVLEVzhyts
        +oGAMUg22qRQBljQxeczm2t7XL5bU+vE5JSsc0YpmHNc4FtvrajtJw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-11T19:42:48Z"
  mac: ENC[AES256_GCM,data:NQBTnChNJAKmDR+2xd638V0io73nURpfIqkNZof6SjsVFEd9QmrH6gEvm7/IjRFMEhTKo73Vy8Eqb545wZxhDnKXTWxvakyd4RsjYlLHhG9jiaifp2coTasLsJcCwxTLjbdsrOUjv+i3esRbgnLn0qdZSZtXgvInO0XT+Nhc7FI=,iv:iT3NQ7GDs37CM2DW+DyzLIweRx2TAzm5HW5xE6qYprU=,tag:o0FaXTnzb7orT89RXhlREw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
