# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:dMPQh9Aaos5Bam1aadDdIJCKhjmV70dcG3Yp32KIbtIHk0ow,iv:NqkMotrDRZpQZSbJHltyFL6lIK/oQAjYDg/HMixImvw=,tag:SXqNTsjg5aYBAsU0A1jKAA==,type:str]
  credentials.json: ENC[AES256_GCM,data:gckUcRVr3G3orKhfk9Cl5EMreJvmpuq1SzQp3SMN/QzrEl12oOl58o4dZ/gD5itq8StE1Om07RbJK8dMSpjEQ3CedR0fhgaDnfkFLD671nF5aoz3U5758wgJs7eQiDQgxJeV/mSQMGUeJDAgHwaxi2tweG9QliqonKIPARH9KpnGe5CPgatBVbIyMYYSQvw5DrLB00lbMUW6HpUAnOqt7GIgQZeCyERpJtOzYw8snA==,iv:8ou0ABRfDstVAviDzOWnGui/jDREdjzHvyg2oIXpfxs=,tag:HysT8Ughf6wYK9t0MFphTQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age17hf2h7uc36snm6hta9l93duhyx6h4q7q8lt9fa89uu67jnajrpts24v5w2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZV0E3L2R6ZDNacFBFVEpB
        MHJWSlJONTR4RG9IeUM2ZXZ2WVlWTXJjMlcwCkVwWEJyNlNTY3owNS84YjFQT1pJ
        WVB0MlFGYks4cHUyMW5Dd0ttcFlyUXcKLS0tIEJlZm9iK1pqR0VZUVgrdjVoZ2sr
        aWdRS3VZdHhFaE5VOFBoeGtPdmtqWjAKVLzmYrAjZpoUSr31GfBd/Yn/UxbFvJoe
        Xe0eaFK/3l7NjOPywK712mZxb81HTvw+9nmM4WOeHYZW5DeJ3jCgxA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-11T19:07:44Z"
  mac: ENC[AES256_GCM,data:4m36mCehCDn2Iyw+k+nKfqxPg7VEPzNXTLjFLeRHcUJU+yCA8chgik3CqSJWPEb8jo/CCeWofYkMjsF0ilMsx2MgWSHlpRXfhlLaQrbqmsabuGvfSISOQVaNQgN/ahdURrVT6xA/Dc4cQ6PT4YTDYT/TBLTliZ957w8a+TttiO4=,iv:Qu3GiCZjgMxG5vC0YCbxpFFkjm6JinMDxEKjAg/qP80=,tag:1fDhrWOOfhHxOvnGRJQLOg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
