---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-external-secret
  namespace: system
spec:
  target:
    name: grafana-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "{{ .authelia_grafana_oauth_client_secret }}"
  data:
    - secretKey: authelia_grafana_oauth_client_secret
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 94348ad9-8138-4bf5-8c54-b0490134df30
        property: authelia_grafana_oauth_client_secret

