apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:McdT2ePZD5KvcmDkHD41cOfSyFzoMwIN,iv:hyK3RkiOzORPw2sNz6rLSjBRD4+AWDHm5ACibTbA14E=,tag:xQ2Aeq2iata3xNBOuLQz+w==,type:str]
    admin-user: ENC[AES256_GCM,data:Gbi5mAM=,iv:8EqTlQ6EG9zAvupmGAJ8hxSlVvZQfn5toBFtCa8Io8k=,tag:JRJMt43hGEsF4b7rWcu+vg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x05r8tdwj7ruzqffcuamt3v7gnf82ldcmrjq8zd3fnh9593grd8sktr4ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4SHI4bTNFd3F3NUZXYTQr
            YjlOT1dSYlNUa0E3N2IzTkltemlNam4yaDJzCjJzYXZzaTNOWFNQOGcwclY4NExy
            RUZRM0d0L3BReW1rR0JaYzVVQ3kxdXcKLS0tIERBbUFZZXpZblVDNS9LdkNwWkRi
            cmV1L3Vrc3J1ZGZpUEwrT2pYWEI2WTQKCHhwsnBLPkDpad1j42V3Fyh8IjGsGA2J
            4NyrnhRwdz/nJo7DnbOzkw971c4OXivXugTwghFPYlfRWZ7/yUd/hg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-18T11:49:44Z"
    mac: ENC[AES256_GCM,data:LK+53M+HTaN67VwX1FnecV66QscHpV9IX9RsFsZJDGoKHGEKaY7gAbmWFkIuvveQdyShxu0lnZzfFcKRXw6zGl1PEr+BFBirsSQwb7yZAZfVtAaJAHi9HvnAaMjrBoWn9O/LyTda6jdu1/G3hnv+/oGWtF3PPerdpn7INlQfuz4=,iv:ZwWf0JH9T4XONzcR7zm3DdTB6ghW9U7qJwN+XQBvbsY=,tag:fg6Si+BRwGy7whbyvC71fg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
