---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zipline
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: zipline
    template:
      engineVersion: v2
      data:
        CORE_SECRET: "{{ .core_secret }}"
        DATASOURCE_S3_ACCESS_KEY_ID: "{{ .key_id }}"
        DATASOURCE_S3_SECRET_ACCESS_KEY: "{{ .access_key }}"
        OAUTH_DISCORD_CLIENT_ID: "{{ .discord_id }}"
        OAUTH_DISCORD_CLIENT_SECRET: "{{ .discord_secret }}"
  dataFrom:
    - extract:
        key: zipline
