---
apiVersion: gatus.io/v1alpha1
kind: Gatus
metadata:
  name: &name zipline
  namespace: ops
spec:
  endpoint:
    name: *name
    group: guarded
    ui:
      hide-url: true
      hide-hostname: true
    url: https://zipline.${SECRET_DOMAIN}
    interval: 1m
