---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app zipline
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      zipline:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/diced/zipline
              tag: trunk-3.7.11@sha256:b3cc87cbb8fd50c3df08b9006e60235d544b7b7f1155a6bbd549a166a2961a29
            resources:
              requests:
                cpu: 10m
                memory: 200M
              limits:
                memory: 4G
            envFrom:
              - secretRef:
                  name: zipline
            env:
              CORE_DATABASE_URL:
                valueFrom:
                  secretKeyRef:
                    name: db-zipline
                    key: POSTGRES_URL
              DEBUG: "true"
              DATASOURCE_TYPE: s3
              DATASOURCE_S3_BUCKET: zipline
              DATASOURCE_S3_ENDPOINT: ${SECRET_CLOUDFLARE_ACCOUNT_ID}.r2.cloudflarestorage.com
              DATASOURCE_S3_REGION: WEUR
              DATASOURCE_S3_USE_SSL: "true"
              DATASOURCE_S3_PORT: "443"
              CORE_RETURN_HTTPS: "true"
              CORE_HTTPS: "true"
              CORE_HOST: "0.0.0.0"
              CORE_PORT: "3000"
              CORE_COMPRESSION_ENABLED: "true"
              CORE_COMPRESSION_THRESHOLD: 200mb
              CORE_COMPRESSION_ON_DASHBOARD: "true"
              EXIF_ENABLED: "false"
              EXIF_REMOVE_GPS: "true"
              FEATURES_INVITES: "false"
              FEATURES_INVITES_LENGTH: "16"
              FEATURES_OAUTH_REGISTRATION: "true"
              FEATURES_USER_REGISTRATION: "false"
              FEATURES_HEADLESS: "false"
              FEATURES_ROBOTS_TXT: "true"
              RATELIMIT_USER: "5"
              RATELIMIT_ADMIN: "1"
              UPLOADER_DEFAULT_FORMAT: RANDOM
              UPLOADER_ROUTE: /file
              UPLOADER_ADMIN_LIMIT: 100gb
              UPLOADER_USER_LIMIT: 500mb
              UPLOADER_DISABLED_EXTENSIONS: ps1,pdf,bat,exe,sh,fish
              UPLOADER_DEFAULT_EXPIRATION:
              URLS_ROUTE: &shorten /g
              URLS_LENGTH: "6"
              WEBSITE_TITLE: Zipline
              WEBSITE_SHOW_FILES_PER_USER: "false"
              WEBSITE_EXTERNAL_LINKS: '[{label:Admin: Aumer,link:https://${SECRET_DOMAIN}},{label:Powered by Zipline,link:https://github.com/diced/zipline}]'
              WEBSITE_SHOW_VERSION: "true"
              WEBSITE_DISABLE_MEDIA_PREVIEW: "false"
    service:
      app:
        controller: *app
        ports:
          http:
            port: &port 3000
    ingress:
      app:
        className: internal
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: "100m"
        hosts:
          - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
      shorten:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
          nginx.ingress.kubernetes.io/custom-http-errors: "400,403,404,405,409,410,411,412,413,414,415,416,417,418,421,425,431,451,500,501,502,503,504,505,506,510"
        hosts:
          - host: m.${SECRET_DOMAIN}
            paths:
              - path: *shorten
                pathType: Prefix
                service:
                  name: zipline
                  port: *port
              - path: /view
                pathType: Prefix
                service:
                  name: zipline
                  port: *port
              - path: /r
                pathType: Prefix
                service:
                  name: zipline
                  port: *port
              - path: /file
                pathType: Prefix
                service:
                  name: zipline
                  port: *port
              - path: /api/version
                pathType: Prefix
                service:
                  name: zipline
                  port: *port
              - path: /robots.txt
                pathType: Prefix
                service:
                  name: zipline
                  port: *port
    persistence:
      config:
        type: configMap
        name: homepage-config
        globalMounts:
          - subPath: bookmarks.yaml
            path: /app/config/bookmarks.yaml
          - subPath: docker.yaml
            path: /app/config/docker.yaml
          - subPath: kubernetes.yaml
            path: /app/config/kubernetes.yaml
          - subPath: services.yaml
            path: /app/config/services.yaml
          - subPath: settings.yaml
            path: /app/config/settings.yaml
          - subPath: widgets.yaml
            path: /app/config/widgets.yaml
