apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:eyRqnR034ZrDpZCi6hJX8GFU7fQe79ra,iv:0i2/6CqhqBPpz2nGa6AwgR++pV29D5xfbXjOZh4DCzs=,tag:vZIgEcyPWRo1q6+nHYaLZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x05r8tdwj7ruzqffcuamt3v7gnf82ldcmrjq8zd3fnh9593grd8sktr4ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGeW03djJJUDM1SU1GUVFJ
            U1JjQURPL3dIQ0tEZk16UnVMV2pyUTJONkY0Ck1OUmU3U3ZpQVFiL3YzdnZPVFpj
            L25tSCs3UUQzZ05uOXBwa09CTWV0NDAKLS0tIFRIaEc0ZVJrQmppN01ESlR0SFVu
            bTRKRWpEb21RamhlNlJtTkJBbEdtUWMKMjuZYQYNExv4DuVkLlfke9U+LjNaJvSW
            jcw9lR6DJVe4kZq4IszC6bZQO71p2BrD2K12yxWqeFZcl8zHGXw52Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-18T12:11:15Z"
    mac: ENC[AES256_GCM,data:O8RA0uinEzGbTMYupa3KyorT8zonvSBzA1WJIGZkQY895BLRtHgoCfxZ31ZDYqQfcjnY7U1eQJI02BWOo7mjVNzUhcvVodM5VnuVGtFPRjvfUFkIsS79LyQe5CvhZ4oavI7v7dbcDy16icQSFlfx7+WthPJPbp02U/NVgh8uK30=,iv:wi/Z6A4Huf0iQVmDleeTrc5sMO5j1cOlHH3tXVn3S3g=,tag:Y65k/wFJ9evd4x0202jWGw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
