---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: paperless
spec:
  components:
    - ../../../../components/kopiur/backup
    - ../../../../components/kopiur/secret
  dependsOn:
    - name: barman-cloud
      namespace: database
    - name: cloudnative-pg
      namespace: database
    - name: envoy-gateway
      namespace: network
    - name: kube-prometheus-stack
      namespace: observability
    - name: onepassword-connect
      namespace: external-secrets
    - name: postgresql-images
      namespace: database
    - name: valkey
      namespace: database
    - name: kopiur
      namespace: kube-system
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 1h
  path: ./kubernetes/apps/administration/paperless/app
  postBuild:
    substitute:
      APP: paperless
      KOPIUR_CAPACITY: 10Gi
      NAMESPACE: administration
      PG_BACKUP_BUCKET: pg-paperless
      PG_MAJOR: "18"
      PG_SSLMODE: require
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: administration
