---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        name: bjw-s
        kind: HelmRepository
        namespace: flux-system
  values:
    nodeSelector:
      intel.feature.node.kubernetes.io/gpu: "true"
    automountServiceAccountToken: false
    controller:
      type: statefulset
    image:
      repository: ghcr.io/onedr0p/jellyfin
      tag: 10.8.10
    env:
      TZ: "${TIMEZONE}"
      JELLYFIN_CACHE_DIR: "/cache"
    service:
      main:
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 10.10.1.234
        externalTrafficPolicy: Cluster
        ports:
          http:
            port: 8096
          discovery:
            enabled: true
            port: 7359
            protocol: UDP
          dnla:
            enabled: true
            port: 1900
            protocol: UDP
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/icon: "simple-icons:jellyfin"
        hosts:
          - host: &host "jellyfin.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
      supplementalGroups:
      - 44 # video
      - 105 # render
    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 20Gi
        storageClass: longhorn-config
    persistence:
      media:
        enabled: true
        type: nfs
        server: ${SECRET_NAS_IP_STREAMING}
        path: /mnt/rpool/media
        mountPath: /media
      transcode:
        enabled: true
        type: emptyDir
      cache:
        enabled: true
        type: emptyDir
    resources:
      requests:
        gpu.intel.com/i915: 1
        cpu: 100m
        memory: 1000Mi
      limits:
        gpu.intel.com/i915: 1
        memory: 6000Mi
