---
kubernetes:
  children:
    master:
      hosts:
        iridium:
          ansible_user: aumer
          ansible_host: 10.10.1.1
        polonium:
          ansible_user: aumer
          ansible_host: 10.10.1.2
        astatine:
          ansible_user: aumer
          ansible_host: 10.10.1.3
