---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: litellm-secret
    template:
      data:
        DATABASE_URL: 'postgresql://litellm:{{ .POSTGRES_PASSWORD | urlquery | replace "+" "%20" }}@litellm-rw.ai.svc.cluster.local:5432/litellm?sslmode=require'
        LITELLM_MASTER_KEY: "{{ .LITELLM_MASTER_KEY }}"
        LITELLM_SALT_KEY: "{{ .LITELLM_SALT_KEY }}"
        OPENAI_API_KEY: "{{ .OPENAI_API_KEY }}"
        REDIS_PASSWORD: "{{ .VALKEY_PASSWORD }}"
  dataFrom:
    - extract:
        key: litellm
