---
web:
  port: ${WEB_PORT}
storage:
  type: postgres
  path: ${POSTGRES_URL}?sslmode=require
  caching: true
metrics: true
debug: false
ui:
  title: Health Status
  header: Health Status
  logo: https://raw.githubusercontent.com/aumer-amr/labv2/refs/heads/main/raw/amr.png
alerting:
  discord:
    webhook-url: ${DISCORD_WEBHOOK_URL}
    default-alert:
      description: health-check failed
      send-on-resolved: true
      failure-threshold: 3
      success-threshold: 3
connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m
endpoints:
  - name: status
    group: external
    url: https://status.${SECRET_DOMAIN}
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions: ["[STATUS] == 200"]
    alerts: [{ type: discord }]
