---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflared-public
  namespace: networking
spec:
  endpoints:
    - dnsName: "external.${SECRET_PUBLIC_DOMAIN}"
      recordType: CNAME
      targets: ["${SECRET_CLOUDFLARE_PUBLIC_TUNNEL_ID}.cfargotunnel.com"]
