apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret-public
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:JvXTjBrKUYNArSNNNuK8QhMcYZSgdi5YsBd5nR3yAq4DKKn9,iv:BJQs/k1Q8vdHNRNTS92YeL6k0hetnv5JyiYu4YZaYXA=,tag:AA3MHM3RUtpwvjZDton/3A==,type:str]
    credentials.json: ENC[AES256_GCM,data:Wi6yw900cRE5GG1u2lvLpb3Oj7PfreGRW4TyuNb91y/ASekeIX8+zhzKxJDgrxyGLuWTK5XAdbPXyHlz9TjylLA+jStcGBfcEIhBP4KCEP2PEn7zzg8WT/VhoQM5X3OHV1eYLhRZeEDYE5e4rWSjROz7dGhPDVTtbcy7RJdtWZyTBlPJi/Y9oSKoavDK2EP2POGlpi3zwP+sRGnXY72xu3hhEw7NXAuwAX+Zrmjs8g==,iv:2BzqFZeiYu580UxZR1jbWtrIiQiO9/M/pIVux+EjBFk=,tag:nPdi6RF3FF+qfVHQk3adWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x05r8tdwj7ruzqffcuamt3v7gnf82ldcmrjq8zd3fnh9593grd8sktr4ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVmk0bFh0aVQybTZrUFdQ
            UlNMT3E4NTBIYXk0V28vNFoyNXdyaGEyeXpRClIycjkrMzRFN1U3SWY5dWtwZXVT
            TlFRcWZrb3pHQ2QxbkNSV1dSSlhRejQKLS0tIDJCK0lmQWxyL1k0QjJzdlV1WnMw
            cm5DYTF2MkhpaVgxa1A1bFV5VzI0UVEKirLW8lH/OXY7btLgwk9jILYQGNBAqeoE
            Oipxs7i7AnjGD667frIpl5t51/wtaWV4gI7HYeahd+wx0q9JuQ1rPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-16T19:53:45Z"
    mac: ENC[AES256_GCM,data:zbhwJHEVBA1z6kKya+ly+T4mcifIumStqlVh9fkukIP4uAcmPLnZ8eamO5+c9mL1N4ox1fzTuYBrElqfQ27zuMjbWYk4+7co0dK7P3iVksd+wJp4AL4GDXu7+cw7wAUEpl8Ui6J8yUN+hVm5mPDv17Z+WlbCavcCTTQSYATLWE4=,iv:pmkk0FpzmIfXEcYBDLqF2o4jbsIrOZtlTwmtsizqA64=,tag:Ds3vSeDzaOGiklKttdhx7A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
