---
ui:
  title: Health Status
  header: Health Status
  logo: https://raw.githubusercontent.com/aumer-amr/labv2/refs/heads/main/raw/amr.png

alerting:
  discord:
    webhook-url: ${DISCORD_WEBHOOK_URL}
    default-alert:
      enabled: true
      description: health-check failed
      send-on-resolved: true
      failure-threshold: 3
      success-threshold: 3

metrics: true

endpoints:
  - name: P1
    group: internal
    url: http://10.40.123.98/
    interval: 1m
    conditions:
      - "[STATUS] == 401"
    ui:
      hide-url: true
      hide-hostname: true

storage:
  type: sqlite
  caching: true
  path: ${GATUS_CONFIG_PATH}/gatus.db

web:
  port: ${GATUS_WEB_PORT}
