---
apiVersion: gatus.io/v1alpha1
kind: Gatus
metadata:
  name: grafana
  namespace: observbility
spec:
  endpoint:
    name: grafana
    group: guarded
    ui:
      hide-url: true
      hide-hostname: true
    url: https://grafana.${SECRET_DOMAIN}
    interval: 1m
