apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: network-policies
spec:
  dependsOn:
    - name: pr-reviewer
    - name: coredns
      namespace: kube-system
  interval: 1h
  path: ./kubernetes/apps/actions-runners/network-policies/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: actions-runners
  wait: true
