---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/litellm.home-operations.com/litellmvirtualkey_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMVirtualKey
metadata:
  name: memini
spec:
  keyAlias: memini
  models:
    - gpt-5.6-luna
    - qwen3-embedding
  proxyRef: litellm
  secretKey: LITELLM_API_KEY
  secretName: memini-litellm-secret
