---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-qbittorrent
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-longhorn
    - name: cluster-apps-nginx-internal
  path: ./kubernetes/apps/downloads/qbittorrent/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 3m
