---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: ${APP}
spec:
  extensions:
    - name: cube
      ensure: present
    - name: earthdistance
      ensure: present
    - name: vector
      ensure: present
    - name: vchord
      ensure: present
