---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: immich-config
    template:
      data:
        immich.json: |-
          {
            "oauth": {
              "enabled": true,
              "autoRegister": true,
              "autoLaunch": false,
              "buttonText": "Login with Kanidm",
              "clientId": "immich",
              "clientSecret": {{ .KANIDM_CLIENT_SECRET | toJson }},
              "issuerUrl": "https://idm.${SECRET_DOMAIN}/oauth2/openid/immich",
              "scope": "openid email profile",
              "signingAlgorithm": "ES256",
              "tokenEndpointAuthMethod": "client_secret_basic",
              "mobileOverrideEnabled": true,
              "mobileRedirectUri": "https://immich.${SECRET_DOMAIN}/api/oauth/mobile-redirect"
            },
            "passwordLogin": {
              "enabled": false
            },
            "server": {
              "externalDomain": "https://share.${SECRET_DOMAIN}",
              "publicUsers": false
            },
            "machineLearning": {
              "enabled": true,
              "urls": [
                "http://immich-machine-learning.home.svc.cluster.local:3003"
              ]
            },
            "newVersionCheck": {
              "enabled": false
            }
          }
  data:
    - secretKey: KANIDM_CLIENT_SECRET
      remoteRef:
        key: immich
        property: KANIDM_CLIENT_SECRET
