---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./httproute.yaml
  - ./networkpolicy.yaml
  - ./ocirepository.yaml
patches:
  - path: ./postgres.yaml
    target:
      group: postgresql.cnpg.io
      kind: Cluster
  - path: ./database.yaml
    target:
      group: postgresql.cnpg.io
      kind: Database
