---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system
resources:
  - ./helmrelease.yaml
labels:
  - pairs:
      app.kubernetes.io/name: theme-park
      app.kubernetes.io/instance: theme-park
