# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:+99DeuuwG00x,iv:yERCuWlrtcggvrGkg3y1PlOQUOcLtZMCFlGW7kFs9c0=,tag:K0KbKwIlMi4q8YxOfNWFsQ==,type:str]
  SECRET_ACME_EMAIL: ENC[AES256_GCM,data:gPl+7I9JA2EJ3yULF7eUaZ4EY4928VrF,iv:gWYuoD+Hp7BGNMkUwx9t/C8ZVsMZAioUGzkV7IBfkfo=,tag:p1ChgVGJS4HPpUdOWF05IA==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:oyxlO+D6h1gRTlcGhhddEIk1AWjjT79DGExv+PdExW4AI5pF,iv:fx6yU5w1N5ZRNEpRd+Y4BzBtvPrUMAGW18D7zSFq5w0=,tag:qA/xzE3TAG2Kp3W0ztLXuQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age17hf2h7uc36snm6hta9l93duhyx6h4q7q8lt9fa89uu67jnajrpts24v5w2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNTkpKeG5RdWhOczErbUdh
        WHVLQWlYb2ZuS0tHWlR0dkxUSkpIVGw5WlRFCk95SWVwNGVhQmpINHM1R2JKWVph
        NmdYRnpaOHhGUlBEWmZtWmtTU2xwcTQKLS0tICs5UWtoTCswZkJLWFZFamt1a0My
        MCtqeU1DangzaFBTR0lYUFJibjJiMU0KUioEuE+UrXNK3j/41pPejSHdz6mycOAX
        dzgdQmqyYOMuOs5IlDC855LRpDMm6wtYAoMpe05rTPg78zz7+yuJiQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-11T17:49:37Z"
  mac: ENC[AES256_GCM,data:ft/HU7FzRBfR8FbpzpaQm+TFsYp3VkKFo/12wIiRBaNnglQeoT3TDNb9bi8bRTrpqXIIHNc92pWdaPHRkxNxEtw5NLtsZ/WTibf8xrwN6/fzAwyFEJ2d4VZn2vijxEgzadS1VD89fHUrZlOluYb3yK0CwumcBbjmCfhAagWM8dU=,iv:buqV/DlbOdPfWTIqUA3H1W5OlOVk7tpGLr/qlGhl1LA=,tag:5mXW09Oc/ujoxeuumGmL1A==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
