# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-extra
    namespace: flux-system
stringData:
    LATITUDE: ENC[AES256_GCM,data:H2KpjYbrv4rJ2A==,iv:dep46O6eZs1pC+QaV5U15NYDPxp97aujVSzX+CnJ3es=,tag:J0Hfp/angYtP+4f58OEvPA==,type:str]
    LONGITUDE: ENC[AES256_GCM,data:GkgDE/4lppQ=,iv:IQRO2/w/gbKKU1u2Gj+tkNM5nVP0vqwYI20Vb7Fz5FA=,tag:phXJC77cecbh868ubEKUpg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17hf2h7uc36snm6hta9l93duhyx6h4q7q8lt9fa89uu67jnajrpts24v5w2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSlhoWmkvWE1QUlZUS3Uv
            eXJTb2FPY2VhTElPMjBKMnVWeDNKL1pTM1FvCjVQclhURnBqbUJaVmg3dG5wSDUw
            Y2piUmtCaWJGNlU1UlFGa25CTEtYemMKLS0tIHR6RTR3bjVlN1g5UitsWlVJckhX
            UGo4Zm1QZlc3UFhCZEZjeEExVVZycVUKWUo3z4cUtvDSeCSp9RD9ranbR5FA4UFt
            Nb2NNo7aliCti9ZRmGVaTP0cmqPKXkaHTVoAqdaXdth/zV6taT6owQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-12T20:50:52Z"
    mac: ENC[AES256_GCM,data:7E8FpkJKSTJdrqlEzRvOcXKX1vt1QcpylP7tOaj6oRmrdgg0MBsGPbEheAtqyBsstAjkQrmLPZ4ezYsMFoU7h8QBfvAWFSqDq2ADt46ZUn3Pm6Q2vGVomdVxs39ck75DYYYpkQUO0tXNV4ICNQngxMhlDRmZlkPWkxx1O9LClP4=,iv:qWDF4pr8z7VN+rhoOgZDGBjwjn4OM/3uYs5MtFmDH7g=,tag:GRjAoVN7Dq/xNjXz2uBR0A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.3
