# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:UCv1lccq8YLF,iv:VYf3tMpoFB0nCKXQYwQATMpokLEpDHV7ebzDGvFVCQU=,tag:gV/rBF20/oJ8X+dVH8cJIg==,type:str]
  SECRET_ACME_EMAIL: ENC[AES256_GCM,data:imq4ApalxU+P6YyV98Fz31LbT1rmz8wB,iv:aTcOc4X1NSY/Jipe8r1O2bXkmhMXxSIdFI+Nq9IyIao=,tag:y1NEONpG9qQERTneRR4VHg==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:piEFxFcCpqAIuPFMZdmPDCLdMpZieyg4RHmMeEvWe2Lm2cHz,iv:sHM3V+7ghR4BcX5cx8diu10xwYzv4GHx5FxCYl7tmMc=,tag:ZzmBoIlB4Ok06Jpnj/1ngQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age17hf2h7uc36snm6hta9l93duhyx6h4q7q8lt9fa89uu67jnajrpts24v5w2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0b29WdkQxcU5ycWgxTTFu
        Z3RDV2hRM2ZNSlR0Ymp3ZlNLZ05ZUlpLUWpVCkI2UGFXcDUxTWFMVUc1NEErZXFv
        S2hPSmNGT3V6djFZT0hOeUgrVUF2NTAKLS0tIDU2bzhiZUJZbGpVVExVendRV1da
        by9NcmJCYTJOSk9uaFVmMm0vNjRXdnMK/AD2+rAtlcTxRsScQfhc1OBsprn6iEpG
        RydopIhUt8vJnCcWfWMoy8iyilnMZNnbywhwzT8WidKxhT8oYCyPig==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-11T17:27:21Z"
  mac: ENC[AES256_GCM,data:xlSG77y2semqxHWozImhYm0hwiZUT1v3R8oFeqHqCG8cC5bVKBYmP3I38wHW10Yzxp/C4WayGCr0XS/sknUSU6BiOeQAPlH2L10JZad6YgMB+zFspk516qkuqLdOfLawCPM/dwc0gOI/VzalBQ8ijXIVfTw7LO0Sp5C9qAeBOSk=,iv:hGOpSaG1XTVSdrzOQODU3STFk323kcrFyzdfOVR1PlA=,tag:7K0EW1JxO5517SyEIi5ibg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
