apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emby
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: media
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/onedr0p/emby
      tag: 4.7.13.0@sha256:b6fc6bfd29b34429d0fcf39c37611ae583f3c2997281d1739ec24bacaa0220db
    env:
      TZ: ${TIMEZONE}
    service:
      main:
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 10.10.1.233
        externalTrafficPolicy: Cluster
        ports:
          http:
            port: 8096
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/icon: "mdi:emby"
        hosts:
          - host: &host "emby.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
    nodeSelector:
      intel.feature.node.kubernetes.io/gpu: "true"
    resources:
      requests:
        cpu: 100m
        gpu.intel.com/i915: 1
        memory: 4G
      limits:
        gpu.intel.com/i915: 1
        memory: 4G
    persistence:
      media:
        enabled: true
        type: nfs
        server: ${SECRET_NAS_IP}
        path: /mnt/rpool/media
        mountPath: /media
    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 20Gi
        storageClass: longhorn-config
