apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: tcp-tracing
spec:
  kprobes:
  - call: "tcp_connect"
    syscall: false
    args:
      - index: 0
        type: "sock"
  - call: "tcp_close"
    syscall: false
    args:
      - index: 0
        type: "sock"
