apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:LKGgUnk5dwU9UN4TnfG4DRClCGJN5dPcyjAHwlu9MzOaQ37VN2I7MA==,iv:8YT4f++jIg4h6c9ztZqIf0SB+dCfN1oIlWApJ4ogORE=,tag:51oBg8x31BA9gDxTvD02yQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x05r8tdwj7ruzqffcuamt3v7gnf82ldcmrjq8zd3fnh9593grd8sktr4ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3czlxbC9nNDJpRXlSTmNq
            MHFVODNDYStQTGlMV28zZ0ZmR2V2RnRuTkQwCjJmbXpqc1BTbk5JNFlkSEFaSXhF
            MFJLcXFOaGVmeHFZNzlWRVBvRnhYWG8KLS0tIDdBb1NtcTJaYm9ZaTUxUmhkbFJT
            NXNQa0NjOERiZHdndmVWbEw2MzI5Q1UK2hmKTGE158ucv+M4GQKqCvxbEvRFjYhE
            xbod695HtE0uzyFmXyN3aNxW5fPlqa34fRFyoBuObMgXCPEfCjbXOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-18T11:49:36Z"
    mac: ENC[AES256_GCM,data:66kQht9nRNd8aR7iqBQcV4ilLjQTEBXQXAqm0avm5oLZwy2O/a3UjgxqoqYYNwFw8msG05SEzl61nFtHUftqwS81rQorKlV1wuAZVWJz48Vj4NTxRyZbYsu5xpfALgEZUQlb5lkHPF9mCZLhAdvJQT6QfO0JvJVSlIwGnXRjJdU=,iv:tmimHpoBfDDya2prYeZg4JAr0eiuqul1WkuBiPeOTU0=,tag:xwPT/Tfryp/df5pKiRmkQA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
