apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:4Wx8GzlrBU7Tq1NV7SOPNAq0VrqiD9p1/cjjd5TEFXnWvTrVv+VVoA==,iv:4cY1oA9r3WBokw7BZ3wd+7zgE/+tgX0xHqs1qwvLSGw=,tag:vsnG3OAPkiPQpcLwRxUebw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x05r8tdwj7ruzqffcuamt3v7gnf82ldcmrjq8zd3fnh9593grd8sktr4ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQMmM1bVJETTIxdUZXeitF
            cEN3VEFKTDlJNjdtTVdxYnJvQzdON1pLOTF3Ck5KTWRXRzFHNDk5ZmRUOXFNbEU4
            Q1Rzd3cxdFJJcDA2MW9rTXFhcU9HVDQKLS0tIHZKZTJPN2sxZWxzdnAzVmw0NHlq
            bitZekZNMDBMcUhzSitPQ3psZnFOTE0KFe8jI3L5u1B11McNXceW2RCdJEm/lmoQ
            O4p0kiiUKNpaJDaebgIWkWvptqUGhmAxXoVswadsGjvePUVY+tl8rQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-18T11:38:33Z"
    mac: ENC[AES256_GCM,data:uAM899qkJXzA7sjIRJCoaPdolNCbLCqPrjlwsJLyKVqJdpWmDsHgOZmJnXXV3vNhV1LGAim01bDxd9fzBFg6l1CpTHwTszP7/bUoQshsh9Tqd1kbrGLCvgPL0iQ8pKnGw0yPi27Y4CGtGcLGNp6icdmk02/e09uA/WaQTpcrRXo=,iv:J+VaY8laV0M5waMrqWTCiJaVlW9UYgm8VlescYgOKlI=,tag:8fs4r1xqvloZtdoKYeoUJQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
