---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bazarr-external-secret
  namespace: downloads
spec:
  target:
    name: bazarr-secret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        BAZARR__API_KEY: "{{ .BAZARR__API_KEY }}"
        POSTGRES_ENABLED: "true"
        POSTGRES_DATABASE: &dbName bazarr
        POSTGRES_HOST: &dbHost postgres-rw.database.svc.cluster.local
        POSTGRES_USERNAME: &dbUser "{{ .POSTGRES_USERNAME }}"
        POSTGRES_PASSWORD: &dbPass "{{ .POSTGRES_PASSWORD }}"
        POSTGRES_PORT: "5432"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  data:
    - secretKey: BAZARR__API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: f7a2a712-c256-4c2d-9d48-b05100e49812
        property: api_token
    - secretKey: POSTGRES_USERNAME
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: b0f64f2d-7a43-4ac2-9b6d-b02e01525324
        property: bazarr_pg_user
    - secretKey: POSTGRES_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: b0f64f2d-7a43-4ac2-9b6d-b02e01525324
        property: bazarr_pg_pass
    - secretKey: POSTGRES_SUPER_USER
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b0f64f2d-7a43-4ac2-9b6d-b02e01525324
        property: username
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b0f64f2d-7a43-4ac2-9b6d-b02e01525324
        property: password
