---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/gitrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: trivy-operator
spec:
  interval: 15m
  ref:
    commit: 14263dd37b3780c7fab9d5d5f2eac8302c44b035
  url: https://github.com/aquasecurity/trivy-operator.git
