---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/gitrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: trivy-operator
spec:
  interval: 15m
  ref:
    commit: 7107830178ae50e96e9f09d98976e51e6152759f
  url: https://github.com/aquasecurity/trivy-operator.git
