apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:VkS+p7r5d91izO8fA1k5nLiXYNdOOdOkKRk1PWY+9MkJhxob1vm1dA==,iv:pA86oyfQk5Rl9Uxoic+6F7R1nGCe7pvg8Y/W3iEYgZA=,tag:q9mrytaTgLN6tDpDk20INg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x05r8tdwj7ruzqffcuamt3v7gnf82ldcmrjq8zd3fnh9593grd8sktr4ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NzhvWDgzSWpvZHFZMlAx
            VVNEaU9vdEI2Z21UMUZTTXBzQnFIRTErQ2dZClJ6Wm51MXVPTWZpS3pKMHZCS2V4
            NVJhVHpOcnhCYzVUa2JZbnJsN21KOTgKLS0tIGhMNExWc00rbzFsRDllOUt6SWU0
            dTBvcG1EL2VvUHVRSm54V3pEdzFVUm8KNoxHr8SADW4E9zWn3sH6biWAyNo6EzPV
            2WpsZFkIBlwRLL5cR1OoVlpmaskC0IoqyMCRMD53T3tso63CfoYjRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-18T11:18:57Z"
    mac: ENC[AES256_GCM,data:qhMKfbXVNoeRW0WKJRq+dOjokBqx33DamK9N1igzQsl4wdpSpEA4A17AoRTvMMn9p/hZCHmNGlOEd2CLotG0Pvy15awlQVSnMD1QnoXLJG+ePnPe3RAGoV/huFF5h9coNJR14rayEA1Jo1fECXufe6qMr1neDtrdOAoqTJzE7Z8=,iv:xA9okWjmgvMx5cNe1cDsywpSOlvWDp0XqMDcoe8G79A=,tag:c16hfCevQpiZycjw9GphHA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
