apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:wGdKve/RL58Cg7gA1qkRkNeloGtgfN0VexVmTjYBbXX/LWAK7jo6Kw==,iv:+EYJ420yoZexWGB2UODAoc5PDjeQ/XGXkFuS0iws4IM=,tag:lLf7ze7q+fOjNGOIntoNkA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x05r8tdwj7ruzqffcuamt3v7gnf82ldcmrjq8zd3fnh9593grd8sktr4ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bXN2OUdCd2pLK2V3RXlO
            OUZycGwrdUZFMGxLNkplMDF1ZmtvQzRCeG1rCm4xTTVRYjB2VkhsZDJPVmtzY0tX
            ZDE4cHpYWHFLMi8wVkxZTG1RUU1VeFkKLS0tIDNQUE80K1FIcFBPVzBCTnd6TXFw
            eHJ6Z2NWdkYwdTlkVHJBSUhOSU1VdWMKR+bdf8LzAaGw4vyB3PZL8/Yzf9oz3scl
            fMIseivCa9VkmGvfWLXymecfHs+2ncGdkNshBezcd3x653c/fpRfDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-18T11:28:54Z"
    mac: ENC[AES256_GCM,data:rLcZCM2Oo6FDeUBHs0K/offBX/yRm3hIxrk1VLg5XLp5iD+oPInUGssBCWoHh1D7EtkHrAeGHDjlfNS3B/Fqp7LdZEqrjN5XDgj9MAyrzpyB4bZtDAHqRpDAZozE0E/Vwh4cxxEAexkIJbay48tGpkqHkKicPMtV0BLxFcAcZsA=,iv:VRxJEUkzTY2T/zOdBmalJ69OFDq/v27P3sFuLVerHpY=,tag:MuYAMCR/zfaTUZE79qYKDg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
