apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:uV3hCv14R/AfaDtfVyHPFOO7AHnYi8OUd6+CQFfHz9Kw4X0fWMn+vg==,iv:SyTJt137y5sHaZ4S/A/SRykrrGRltr10hqwSuMhVkz4=,tag:BYmsHMQXtlqeVA4UZsN3NA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x05r8tdwj7ruzqffcuamt3v7gnf82ldcmrjq8zd3fnh9593grd8sktr4ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZd1FTNHAxRDZwTXRBVzht
            YStKQmc3a3FyZ3JmVUprdWdOcTUxOWlEL1JJCkg1S2NKa0Fta1BXc1ZiNnZpemJ5
            THExOTRDVUdySUEyZlZseHVFQmtwRUEKLS0tIFN6clpWNmY5bkF2RjdSSC9pUmJl
            WWZ5ZTEyWU43R3o2U1RnRmh2b3B5ODAKF0YhamKk5Me8Tt6hkOm8bnJEK2IG+372
            nqbQqy06CucNZnFlFxy4Xk8j3FvOBndO1wQ3PMplkW9bsOhUt6mF5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-24T09:32:32Z"
    mac: ENC[AES256_GCM,data://sKodexIgvvQrpqMfeElBo18PrrRaKDQ6X/Fd48AfXWIl95RYIoV/r66TYzWpBw9d7iqA18lxhgN9FfDp1nbrg3TSPTeroX4bT6quTXtPjLuSxfaeKhqOX8bxWTyDMchY0VPorIRUEjWT4JdOKfGTHpNfGi3+eS1ack3lEsFto=,iv:D64H4pVPKf7lpndt9Vaybb7Tjmpf45Mj0Ykqz1e10/E=,tag:oVHsJF7Yv+NXfMithTpiSA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
