---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gmail-operator-external-secret
  namespace: system
spec:
  target:
    name: gmail-operator-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        credentials.json: |
          {{ .credentials }}
  data:
    - secretKey: credentials
      sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
      remoteRef:
        key: bbe15ea2-dda7-4e06-898c-b07d01235d3f
