---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gmail-operator #redeploy
  namespace: system
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/aumer-amr/gmail-operator
      tag: 1.0.3
    env:
      TZ: "${TIMEZONE}"
    persistence:
      credentials:
        enabled: true
        type: secret
        name: gmail-operator-secret
        mountPath: /home/node/app
        readOnly: true
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/icon: "weather-sunset"
        hosts:
          - host: &host "gmail-operator.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    service:
      main:
        ports:
          http:
            port: 3000
    serviceAccount:
      create: true
    serviceMonitor:
      main:
        enabled: true
        endpoints:
          - port: http
            path: /metrics
            interval: 15s
            scrapeTimeout: 10s
            scheme: http
