---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system
resources:
  - ./rbac.yaml
  - ./external-secret.yaml
  - ./helmrelease.yaml
generatorOptions:
  disableNameSuffixHash: true

