---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prowlarr-external-secret
  namespace: downloads
spec:
  target:
    name: prowlarr-secret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        PROWLARR__API_KEY: "{{ .PROWLARR__API_KEY }}"
        PROWLARR__POSTGRES_HOST: &dbHost postgres-rw.database.svc.cluster.local
        PROWLARR__POSTGRES_PORT: "5432"
        PROWLARR__POSTGRES_USER: &dbUser "{{ .PROWLARR__POSTGRES_USER }}"
        PROWLARR__POSTGRES_PASSWORD: &dbPass "{{ .PROWLARR__POSTGRES_PASSWORD }}"
        PROWLARR__POSTGRES_MAIN_DB: prowlarr_main
        PROWLARR__POSTGRES_LOG_DB: prowlarr_log
        # Postgres Init
        INIT_POSTGRES_DBNAME: prowlarr_main prowlarr_log
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  data:
    - secretKey: PROWLARR__POSTGRES_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: b0f64f2d-7a43-4ac2-9b6d-b02e01525324
        property: prowlarr_pg_user
    - secretKey: PROWLARR__POSTGRES_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: b0f64f2d-7a43-4ac2-9b6d-b02e01525324
        property: prowlarr_pg_pass
    - secretKey: PROWLARR__API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d8952b41-167d-4fcc-9eed-b04f00a580c9
        property: api_token
    - secretKey: POSTGRES_SUPER_USER
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b0f64f2d-7a43-4ac2-9b6d-b02e01525324
        property: username
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b0f64f2d-7a43-4ac2-9b6d-b02e01525324
        property: password
