---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: code-server
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-longhorn
  path: ./kubernetes/apps/home/code-server/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
