apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:bfPq82NMT9G6IBCzOQSEATVB+vrZJ/Jn3hS4iwng3AKFkqbhn0ryCvwKYiXM2MTLvq2SDoGikmQJ/9QYvI+G0UzthYorN7ZVgwQHWWv85CnUYpTr7aYi2GkAN3CjyxWxLjPHq5kjzxwjCEQ7hpuqVDL/jMeja4ahRMOEbYHV+FMCwsBWsXlAtprF6RkQkSKZTnTqstNlgVzcuIvo10r843Sexn2WStnjypzL3lOX22f1PFJB,iv:bZETPe5B/87oGysZ1MbzejTT44m+yczrdD2CVRUkwFk=,tag:9w9aENPMGqF6lp4kbL08oQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5ICtyZlBqLytX
        aEFkNVJhd0hkeHZrMVdaaWN5Vk54YWxZZGlWSmJ5OWlUOWlSUGlvYjhqWUhlWlRx
        emlMdW56TlViMzFiU0JvWU1TRnRiZTIrUDJNM3hxZkNBNU1mczRvUDV1VkdkcjJY
        SlhjaGFkVlVWeGVzSUxFaDZ3YlVBTEpWVGEzTm5zcFpxU2tXOGM0bTJOcnd5anN4
        WWFIdk9vZktyWWh2M3JJQythU3lzQXNUdklHbUlHTk5VdEV5M2JFcTdYSkJZSURV
        VGw4cDhiM2UvaGJ2d05zRUJjbzVwcHZpSFVVTzBOd0dmTGd3ZjRaLzBoRE85c0lR
        QVJjWnhScDNKcndBZ2lTTSt1OFY3S3AzZ08yblVzeUNUTkVvd2FNQzJQZUxITXBl
        QjhNNWV3enZJTGZnMlNwRlMxSG9zT0l4WER4cE5UR25BQzRVVVBQVjAzOUMzYzV6
        dURSNnlXL09BQVpWdUNJZE82dTAvV2Z1eDUwc2dBREk4R0czSzZ6cklKbjBLWU1T
        UkRlR2NTS2JKMlhBd0Y4eG9naW52TUxDTnZCWFg1SmRtdm9GVzN2K3U4WjNZaDdh
        aWpvNFpSaDFGUXpLN1ZBZVVRT3RrU2RMb1BmRVg0c0lNempabUZmSGxIUnNFb0xZ
        aEMwaWxiaTRVVEdvNWdCYTM5SkRsaEFaWUFxY1QrMmVtTjdlTjFMNXZGSmdwb3Ax
        NGFwN2RBaXlXU0dNMUpCa0xpaVArUmhIcmtMQTBJTHYwUDBVcm9LL09CM3plbVRo
        Q01JU0hCWm5EY05WOVJ2VUVVSDYrcCsxNkRxMjg5a1luZ1VnZ25UOUlhK1R5ZlNC
        QkQ5K2V1N3JKYVFGY3FuNUwvOWhURlBDeTJaR0Q0ZHFUdzBEaUtRWlhRaWl2Rnpv
        ckhTdDhNQVg5dEVzVGF1ZHFOMXVxYzNRUmwrTjdkaEY4emZmalp4Rmt4a2lrR0JO
        Q3krNlFkUWNpQ3RsbkRzU2Q2NWxKMERaV3FFa3YrM29kREJKRXo0ZTlFUVVIcWtn
        T2hnTWEwZFpzZmdvZWRLbjhtMVZPbGVkQVRBTDNCb1UrekNQVGgrbGZPaTRZdDR6
        STBDaldsUktnM2FvZ0piYis4dHZZbG80TWhVTkVTM01TdnZSQ1Q5VzlNZW8wT1dT
        TmV4QWJRa1ZEN2NrY0gwQ0xBVEVaVDBmTk94bk1hbVJJL3FvMm53cmlBRTdWbXlI
        aDNOS0tGdEJmUEdEVTRZbXJEeUJhcHNwMTRFRW8zdzFkcHk3eE5qNFlnNE5ORmRL
        L0lGNU1aUnlKYmxrWDY5eXd6ZnkvTDVBVDVVNFNjSXlxeG0rMlZjWXEyUTluMDhU
        UVg2QnppeXBWMnUzY2s2cWErcitqSjNwejJXRFQrRFJ1bDRVZ0VScXAzRWFOVjF0
        QUU1V1lwcTFxSEh0VXNyVzBFeUlSeXdORHhGU0lCVFpxYTYyZnl6UU5PM3pkY3l4
        Yk5haHR3dGdHcnVnNHlrOXljODJ1UkFvbmdsVy96R2NXL1M3UVdXcDVOOHYyNmVk
        cTNnOGJnSzBFNXhWbElxNVJuYW9CTVFtTkFOYThFQ2lmdDBHRW5ESjJUWlU5aFBt
        MWs2dWRBM253ZzNrOEo5QkJwdVRuV2RBZkRoMkxmK0N2RjNjVFoxVUs5Sk9nR1ds
        cVQ5TEJ2dlY2dUlOdU5LdlFKMlM1dExWMTd2NWtBc1dQTzRDa3cyaktFeURWdmNp
        aVF5UFhuTCs4dUM4VmFHWTI1WnB4K21TMENuMTlxZUtZUk8wUldUSmo4S1VPRFJw
        aGZwVi8xbElEcjNJcU1pbSszL1BsT2ZzUlhqZzlwNURHU3BObi91UGcydFp3Znds
        T2VGL3A1ZjJlalczelJvblpJYmN2eHBGSTZNMG1uc0o3NnpicThWRzFnNEFGMFB2
        Z01iSW11T1hFcThnVU5hSjdsSGN0SGxHNm5Lai8wODhYWSttUWxYRGtxZHVJUQpy
        UDN3TWE0L2d3YjZmRXFLUzhYSVFLaGhCVG9PbWZMZlgxRFVKdmtIbHU0Ci0tLSAv
        dWhGVzJ1YmlhSExIdjBzRnFtNUw3Q1A0OFF0QnFyMkJiV1FCNk0wL1ZzChRcaBV4
        q2UO848ipIp3f3KU60XyHoURtOsuN1iUR3GkyJcrZMQnUFmAvu6wyoWb5OxjwSwc
        UEKMkjscTfRDMyA=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1gqj5utvvc0rs900wzyaen9etl26xpk49f49ask0dlzdrcpt2xkakyl75q49esxh8a342s6pwydt668rxgzr7c9ntfv0lmh9z277x6hcsfceefzx0sy8x2u7t3ltt2x4zpck42t9432axlzeqfgaenc0h82yjnzgqezs3x6jurmetk5z88tpzr2at0pv4pekza7dfnx3n54hgsk6tdprac6jx6r2rxzre8mh5dqgd799hety35ed3v593n0f52fuzqcl2395wzqnj29yhkq05s8vcqqtzv2e0s4aun9tzptny3srhpps7zjghpsdrnchsq8rld8vvmsv9cw7yghnf046e46nq5cp893749q9wu6yeaszznxt8z06uhwlsl7323d98te22pacv3nh8r26n2j696nt6arg8hvgwsf4vey9llsugj925fst8j5gw9wmfktymlrzs3xj82rnq9nrmnxqh4sndveu0txppryscxl9c3d9rxc450qrfh9thakf4zn6aevayfs402vtju63530tzj9lygqmuq6jef663p2as47k897nwgp2g7whnsz60l2yf6ljk33g3nd23wsv02yg33v7ge7mmdqj7kvak8v8p65n72qyk5qkjt2u4rfyxrxpjeagf4eex6qurk3dx0rd7mzvvnksd3ygrq5ymxn02sz75qx0dh6gy2qkteeu3pvhqjpwzkc5m5nz9jcdnevext58d9q4h25qzuv2hlnresdhf89an9j7j83n8zw6whjmyxxajklazcm4y23jglvqaudgphsdtqljuqukx8sye59vqm45kjergga9kp8xs63r5lg2xvh4nta8mvrc5fxc6nvgdcsp38jqytpcvhhdw2l70nydk0dr24t65ad28cnn8kl5u7zze8fvn5wfkav7505dms27wq7wqy9pu3pnhzddtfat98fa9sawwx44k06qvzqqupwxhj3f3kan3ecmpwae2cmysstv4x40jns9scx279m6rjsjm3cv9v9fvvzy6gv6awtsx0nqjvx0x8tqp6q3na5ux6utrkncgev4y2kepsnrfj7e6ygwyxm0c2zalj4lc63eptfzhpzyzpqfvcsg0kax3rvy5n7c3gs9yxft4hvpp5yp2m3ztuawfc7t8uqq6s44vqsfrs3rt0c6n332rqwfkn4fxjuzxfza8uypyzue507ath2mr4x4ts2kv0up6gk7pgvdt53v9fxstktxqpp7965e4gdcg5t4mdrxt6g4tuxsny3pugjcyeda0tqau8w4aj6v2e2w9ada99m6w52aqqva2gs4gnrw92ta4ekgrksszs0qdl7qf0kneqhm4gg2pyx4vkfrfhvcd4cj9wqmyzm5hs03jpgjl43pjyk7883ts3e8y9slewg2pl4gzypm6ta2shrr6f0mk2vtnytpe6vs909w6sq6my4sh66pc9wd35an6097pj4d4nwhemv0s3xq9k5g23jcjxcmuykyn89hzcf3x7ptkayxz2d0fp26g2z3z8szn9nw2m0qf0w26qa925357c6vs28pmkqy8fz82jgt8axglvtq9hycksqcmf2lmyvudej0sfxsu3c25xnk3vqx5vv5a58q03v7f256pce9vvtxtrdsrvv82chya4kqegz55p3d5et3t2j8fvqpt5xerdhz42h2e29n6fp56ylzecsur93jfp6g5gjdz8qqqldeyvf9cwzj3509jc3dnl2sr3nqe6srmhf5fzu30qek73fxq439x4722c6kz0k0cwc2lxsytse4d0kyn7kgtyyp5kglxms9sdxtazfa6f0wxxggg0pxculqlzatcvl07exl7e09wm0kuqg0fqapad8csxn363twn2pey0pqdnxt6t87mwkc4fu42j0cz98wqvsry885wles9pv73djqsudtxc7zkxcr3x85s
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-07T14:41:59Z"
  mac: ENC[AES256_GCM,data:zSNsd9QB4Txbo6OFQSe3n5y0xiqcnTWdwrRWri2ZVbp4L4FRwdPSfzBOZgkl0CaPDa69Ll43hWVPEhdlVFCquNNexYNUgz/7QlphPmd9PcQ+pvBPmy017LsP3SLSbN2qpAb4D9EfYy7OqhS88Edt5Pmcmk2EDvk1Clmd6CiiJQA=,iv:ytIVWVLsakM4jCENl8sKmfdRIkVVRBdUleXsxy1CbYs=,tag:Nk26wZ6GWhLEU04IqbIchQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
