---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./litellm-operator/ks.yaml
  - ./litellm/ks.yaml
  - ./llmkube/ks.yaml
  - ./speaches/ks.yaml
  - ./hermes/ks.yaml
  - ./memini/ks.yaml
  - ./open-webui/ks.yaml
  - ./searxng/ks.yaml
  - ./ha-mcp/ks.yaml
  - ./paperless-mcp/ks.yaml
  - ./context7/ks.yaml
  - ./network-policies/ks.yaml
