---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: site
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    persistence:
      assets:
        enabled: true
        type: configMap
        name: site-assets-configmap
        mountPath: /home/node/app/assets
        readOnly: true
    image:
      repository: ghcr.io/aumer-amr/site
      tag: main
    podAnnotations:
      reloader.stakater.com/auto: "true"
    env:
      TZ: "${TIMEZONE}"
      DEBUG: "false"
      PORT: "3000"
    ingress:
      main:
        enabled: true
        ingressClassName: external
        annotations:
          hajimari.io/enable: "false"
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "www.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    resources:
      requests:
        cpu: 10m
        memory: 128M
    service:
      main:
        ports:
          http:
            port: 3000
