---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: site-assets-configmap
    files:
      - favicon.png=./assets/favicon.png
      - logo.png=./assets/logo.png
      - style.css=./assets/style.css
      - index.html=./assets/index.html
      - robots.txt=./assets/robots.txt
generatorOptions:
  disableNameSuffixHash: true
