apiVersion: mariadb.mmontes.io/v1alpha1
kind: Backup
metadata:
  name: mariabackup
spec:
  mariaDbRef:
    name: mariadb
  schedule:
    cron: "0 */1 * * *"
  maxRetentionDays: 14
  storage:
    persistentVolumeClaim:
      resources:
        requests:
          storage: 100Mi
      accessModes:
        - ReadWriteOnce
