---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mariadb-external-secret
  namespace: database
spec:
  target:
    name: mariadb-secret
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        password: "{{ .password }}"
  data:
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 1f46e1b4-5e10-4c03-9f43-b0a8012de4ad
        property: password
