apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
  replicas: 3

  port: 3306

  galera:
    enabled: true
    primary:
      podIndex: 0
      automaticFailover: true
    sst: mariabackup
    replicaThreads: 1
    agent:
      image:
        repository: ghcr.io/mariadb-operator/agent
        tag: "v0.0.3"
      port: 5555
      kubernetesAuth:
        enabled: true
      gracefulShutdownTimeout: 5s
    recovery:
      enabled: true
      clusterHealthyTimeout: 3m
      clusterBootstrapTimeout: 10m
      podRecoveryTimeout: 5m
      podSyncTimeout: 5m
    initContainer:
      image:
        repository: ghcr.io/mariadb-operator/init
        tag: "v0.0.6"
        pullPolicy: IfNotPresent
    volumeClaimTemplate:
      resources:
        requests:
          storage: 300Mi
      accessModes:
        - ReadWriteOnce

  volumes:
    - name: mariabackup
      persistentVolumeClaim:
        claimName: mariabackup
  volumeMounts:
    - name: mariabackup
      mountPath: /var/mariadb/backup/

  rootPasswordSecretKeyRef:
    name: mariadb-secret
    key: password

  image:
    repository: mariadb
    tag: "11.0.3"
    pullPolicy: IfNotPresent

  env:
    - name: TZ
      value: ${TIMEZONE}

  volumeClaimTemplate:
    resources:
      requests:
        storage: 10Gi
    accessModes:
      - ReadWriteOnce

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi

  podSecurityContext:
    runAsUser: 568
    runAsGroup: 568
    fsGroup: 568
    fsGroupChangePolicy: OnRootMismatch

  service:
    type: LoadBalancer
    annotations:
      io.cilium/lb-ipam-ips: "10.10.1.190"

  metrics:
    exporter:
      image:
        repository: prom/mysqld-exporter
        tag: "v0.15.0"
        pullPolicy: IfNotPresent
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 300m
          memory: 512Mi
    serviceMonitor:
      prometheusRelease: kube-prometheus-stack
      interval: 10s
      scrapeTimeout: 10s
