apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
  port: 3306

  rootPasswordSecretKeyRef:
    name: mariadb-secret
    key: password

  image: "mariadb:11.0.3"
  imagePullPolicy: IfNotPresent

  env:
    - name: TZ
      value: ${TIMEZONE}

  volumeClaimTemplate:
    storageClassName: longhorn-database
    resources:
      requests:
        storage: 10Gi
    accessModes:
      - ReadWriteOnce

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi

  podSecurityContext:
    runAsUser: 568
    runAsGroup: 568
    fsGroup: 568
    fsGroupChangePolicy: OnRootMismatch

  service:
    type: LoadBalancer
    annotations:
      io.cilium/lb-ipam-ips: "10.10.1.190"

  metrics:
    exporter:
      image: "prom/mysqld-exporter:0.14.0"
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 300m
          memory: 512Mi
    serviceMonitor:
      prometheusRelease: kube-prometheus-stack
      interval: 10s
      scrapeTimeout: 10s
