---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: immich
spec:
  components:
    - ../../../../components/cnpg
    - ../../../../components/valkey
    - ../../../../components/kopiur/backup
    - ../../../../components/kopiur/secret
  dependsOn:
    - name: barman-cloud
      namespace: database
    - name: cloudnative-pg
      namespace: database
    - name: kanidm
      namespace: security
    - name: envoy-gateway
      namespace: network
    - name: kube-prometheus-stack
      namespace: observability
    - name: onepassword-connect
      namespace: external-secrets
    - name: postgresql-images
      namespace: database
    - name: valkey
      namespace: database
    - name: kopiur
      namespace: kube-system
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 1h
  path: ./kubernetes/apps/home/immich/app
  postBuild:
    substitute:
      APP: immich
      NAMESPACE: home
      KOPIUR_CAPACITY: 100Gi
      PG_BACKUP_BUCKET: pg-immich
      PG_MAJOR: "18"
      PG_SSLMODE: require
      VALKEY_MAXMEMORY_POLICY: noeviction
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: home
