---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tetragon
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: tetragon
      version: 1.0.0
      sourceRef:
        name: cilium
        kind: HelmRepository
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    enabled: true
    imagePullPolicy: IfNotPresent
    dnsPolicy: Default
    tetragon:
      enabled: true
      image:
        repository: quay.io/cilium/tetragon
        tag: v1.0.0
        securityContext:
          privileged: true
        grpc:
          enabled: true
          address: "localhost:54321"
        enableK8sAPI: true
        enablePolicyFilter: true
        enableCiliumAPI: true
        enableProcessCred: true
        enableProcessNs: true
        prometheus:
          enabled: true
          port: 2113
          serviceMonitor:
            enabled: true
    tetragonOperator:
      enabled: true
      podInfo:
        enabled: true
      image:
        repository: quay.io/cilium/tetragon-operator
        tag: v1.0.0
