---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: tetragon
    app.kubernetes.io/name: tetragon
  name: tetragon
  namespace: kube-system
spec:
  endpoints:
    - honorLabels: true
      interval: "10s"
      path: /metrics
      port: metrics
      relabelings:
        - replacement: ${1}
          sourceLabels:
            - __meta_kubernetes_pod_node_name
          targetLabel: node
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      app.kubernetes.io/instance: tetragon
      app.kubernetes.io/name: tetragon
