---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarr-external-secret
  namespace: downloads
spec:
  target:
    name: sonarr-secret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        SONARR__API_KEY: "{{ .SONARR__API_KEY }}"
  data:
    - secretKey: SONARR__API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 2ffbc008-00a8-4f3b-b7e4-b04f00ab14de
        property: api_token
