---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zipline-external-secret
  namespace: default
spec:
  target:
    name: zipline-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        CORE_SECRET: "{{ .core_secret }}"
        CORE_DATABASE_URL: "postgres://{{ .zipline_pg_user }}:{{ .zipline_pg_pass }}@postgres-rw.database.svc.cluster.local:5432/zipline"
        AWS_ACCESS_KEY_ID: "{{ .s3_access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ .s3_secret_access_key }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: zipline
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .zipline_pg_user }}"
        INIT_POSTGRES_PASS: "{{ .zipline_pg_pass }}"
        INIT_POSTGRES_SUPER_USER: "{{ .pg_super_user }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .pg_super_pass }}"
  data:
    - secretKey: pg_super_user
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b0f64f2d-7a43-4ac2-9b6d-b02e01525324
        property: username
    - secretKey: pg_super_pass
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b0f64f2d-7a43-4ac2-9b6d-b02e01525324
        property: password
    - secretKey: zipline_pg_user
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: b0f64f2d-7a43-4ac2-9b6d-b02e01525324
        property: zipline_pg_user
    - secretKey: zipline_pg_pass
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: b0f64f2d-7a43-4ac2-9b6d-b02e01525324
        property: zipline_pg_pass
    - secretKey: core_secret
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: a73bcd47-70ae-4f1f-a4da-b08600c2ad16
        property: core_secret
    - secretKey: s3_access_key_id
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: a73bcd47-70ae-4f1f-a4da-b08600c2ad16
        property: s3_access_key_id
    - secretKey: s3_secret_access_key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: a73bcd47-70ae-4f1f-a4da-b08600c2ad16
        property: s3_secret_access_key
