---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zipline
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        name: bjw-s
        kind: HelmRepository
        namespace: flux-system
  values:
    controller:
      type: deployment
      replicas: 1
    image:
      repository: ghcr.io/diced/zipline
      tag: 3.7.4@sha256:000d61f694d002d94a46b089b4d2617a72fe2cba3c1388ad149233e654625fe3
    env:
      TZ: ${TZ}
      CORE_SECRET:
        valueFrom:
          secretKeyRef:
            name: zipline-secret
            key: CORE_SECRET
      CORE_DATABASE_URL:
        valueFrom:
          secretKeyRef:
            name: zipline-secret
            key: CORE_DATABASE_URL
      DATASOURCE_S3_ACCESS_KEY_ID:
        valueFrom:
          secretKeyRef:
            name: zipline-secret
            key: AWS_ACCESS_KEY_ID
      DATASOURCE_S3_SECRET_ACCESS_KEY:
        valueFrom:
          secretKeyRef:
            name: zipline-secret
            key: AWS_SECRET_ACCESS_KEY
      OAUTH_DISCORD_CLIENT_ID:
        valueFrom:
          secretKeyRef:
            name: zipline-secret
            key: OAUTH_DISCORD_CLIENT_ID
      OAUTH_DISCORD_CLIENT_SECRET:
        valueFrom:
          secretKeyRef:
            name: zipline-secret
            key: OAUTH_DISCORD_CLIENT_SECRET
      DATASOURCE_TYPE: s3
      DATASOURCE_S3_BUCKET: zipline
      DATASOURCE_S3_ENDPOINT: ${SECRET_CLOUDFLARE_ACCOUNT_ID}.r2.cloudflarestorage.com
      DATASOURCE_S3_REGION: WEUR
      DATASOURCE_S3_USE_SSL: "true"
      DATASOURCE_S3_PORT: "443"
      CORE_RETURN_HTTPS: "true"
      CORE_HTTPS: "true"
      CORE_HOST: "0.0.0.0"
      CORE_PORT: "3000"
      CORE_COMPRESSION_ENABLED: "true"
      CORE_COMPRESSION_THRESHOLD: 200mb
      CORE_COMPRESSION_ON_DASHBOARD: "true"
      EXIF_ENABLED: "false"
      EXIF_REMOVE_GPS: "true"
      FEATURES_INVITES: "false"
      FEATURES_INVITES_LENGTH: "16"
      FEATURES_OAUTH_REGISTRATION: "true"
      FEATURES_USER_REGISTRATION: "false"
      FEATURES_HEADLESS: "false"
      RATELIMIT_USER: "5"
      RATELIMIT_ADMIN: "1"
      UPLOADER_DEFAULT_FORMAT: DATE
      UPLOADER_ROUTE: &upload /file
      UPLOADER_ADMIN_LIMIT: 100gb
      UPLOADER_USER_LIMIT: 500mb
      UPLOADER_DISABLED_EXTENSIONS: ps1,pdf,bat,exe,sh,fish
      UPLOADER_FORMAT_DATE: YYYY-MM-DD_HH-mm-ss
      UPLOADER_DEFAULT_EXPIRATION:
      URLS_ROUTE: &shorten /
      URLS_LENGTH: "6"
      WEBSITE_TITLE: Aumer
      WEBSITE_SHOW_FILES_PER_USER: "false"
      WEBSITE_EXTERNAL_LINKS: '[{label:Admin: Aumer,link:https://${SECRET_DOMAIN}},{label:Powered by Zipline,link:https://github.com/diced/zipline}]'
      WEBSITE_SHOW_VERSION: "true"
      WEBSITE_DISABLE_MEDIA_PREVIEW: "false"
    service:
      main:
        ports:
          http:
            port: 3000
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/icon: pajamas:media
          nginx.ingress.kubernetes.io/proxy-body-size: "100m"
        hosts:
          - host: &host zipline.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
      shorten:
        enabled: true
        primary: false
        ingressClassName: external
        annotations:
          hajimari.io/enable: "false"
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
          nginx.ingress.kubernetes.io/custom-http-errors: "400,403,404,405,409,410,411,412,413,414,415,416,417,418,421,425,431,451,500,501,502,503,504,505,506,510"
        hosts:
          - host: &exthost m.${SECRET_DOMAIN}
            paths:
              - path: *shorten
                pathType: Prefix
              - path: /file
                pathType: Prefix
              - path: /api/version
                pathType: Prefix
        tls:
          - hosts:
              - *exthost
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        memory: 4000Mi
    initContainers:
      01-init-db:
        image: ghcr.io/onedr0p/postgres-init:14.9
        imagePullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: zipline-secret
