---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nas-gatus
  namespace: monitoring
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: NAS
        group: main
        url: https://nas.${SECRET_DOMAIN}/ui/sessions/signin
        interval: 1m
        conditions: ["[STATUS] == 200"]
        alerts: [{ type: discord }]
        ui:
          hide-hostname: true
          hide-url: true
