apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:z6YodnA7lYZYYPGSwVPqbgg35Jm5R23rwXjMD6b8HP3JKF/P56KIU5x1MSAsjLdeDP+Um3l7f/a5edD8,iv:vLMoQoItA2/V+ZVPOkMYG/zEQ0DYbRCg1ZYW2LYw4hc=,tag:X6s4z7nmJsWfAo+6Q0Df3g==,type:str]
    username: ENC[AES256_GCM,data:Ay5eac8=,iv:vfdkVE9o8nEp5rVUEaIFTQUXi9zFzjDNn7WY+4lxLw0=,tag:GIiL6zIwe7ltTSjoecQOsw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x05r8tdwj7ruzqffcuamt3v7gnf82ldcmrjq8zd3fnh9593grd8sktr4ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpSmJFeWlYQ3FBWEl6K0xK
            Zklsc2IyMFZLUXg4emxETmR2Y3FWR3hSM0FVCjVFSVJSMk9rVXdhSW1qaVc0TXRu
            RDhFWTRGYnlsSHFPb3FuZS9Dbk82NkkKLS0tIEFDS1MxVGNOUEtHOEdMajJpRCtC
            RytuZ1A4Tk1vcHlCSmh1NzRaaXlYaGsKdOX+g5gwWE6XjDqLVIh1TssmX4oDH4UE
            If8GkxtQ+4Fu/Pd50UaA9CQc1hJMYXpFkOTCcAgbpFKC6lmh1xHFSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-18T11:38:48Z"
    mac: ENC[AES256_GCM,data:9fP1Yjjxh0eSjONtBZ92U0Q3sXsvR4kL0nWomqndZBNRSL0YI9xdhvHjPSsX6Y+ECuihZiL488/6i/vK2kNXqLxEJPsWu7SsgO4I5puWPDIZb8bp7xBbLAUZo+5gu3nRVxKfaUMvWAAqSeu/6Q/q44OxlCv4Idxz7SL3lhUmh2I=,iv:pNqiPbiRGwuvdUJ4iiJrOwtSdhgElcLqw0LX/vdh+h0=,tag:YEpp/gd+HNMouZeNN+ilLQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
