apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:7sE9/3tuf50Icbo/gnWHXNJiy2EQ4ehVzA94w3AgvU3wyQlOFP1UF6HTrPMA684o77BnFVAHChkzzFFK,iv:SB9QMbK2ZpoIVTjq+6vDeNT5VtSIvGdSqLJ5Fcqtz0w=,tag:YFasxaj/XWCyvyfKXL0wfw==,type:str]
    username: ENC[AES256_GCM,data:FOa43vo=,iv:pJKmJViuBDMnmNyXNjRgpTGOijS/HTpjFb+iwbZgTNA=,tag:NB6gnL8+ALIh7R0cqc2KPA==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x05r8tdwj7ruzqffcuamt3v7gnf82ldcmrjq8zd3fnh9593grd8sktr4ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTR0NPVkdZQUltblJxeFp6
            T3dzS1hRS05kWTdKV3E1bytYd1Z2VWR3dFRrCjk3ekhLM3QrNDU3a1VMaGxhb2tw
            eVFKVW4rdURreU5NNGZqVFpVV1I1WkkKLS0tIGpwRmdNLzVHUGJvWm1ENGhuK3B5
            WEw4azJUb0xkMU9PZktGbnVNTFovKzAKUPYexR24TRd1OhBR5/OqkUMCO2pESFg5
            BrzCQh2Yhd/wU6YPFJp4d9lswlf7gPplpTeS8323yYjWRlsT2mcHlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-24T09:32:46Z"
    mac: ENC[AES256_GCM,data:O2k5BHGAXJsYikMxCoqw5xz6kTykkr2svFh/Q/raLuf9+pEIRS3UNi3DCHj6sGNIpLrpOij+hOFEoZSAMMFm0sLyrbCGxLcM0xDINN/2XcQissO3EUfATqtNoegB1U47cLGu0YuMU0P5K/Ax4IlWDKHbTS8y7psdhiqaf3u69Yk=,iv:ChdC3J78JdAmJYtJ/bYro/swqYu+89WzmaoODmNr9Wc=,tag:+/VXcXJ1Mt8/NMDo7GF8yA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
