apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:40FzUfdEoxLDNZUKuPk1tOd43SEjhM5SJSky/eJHb099My+oAF5Gf7/W/5nh+w8837r5ooXavlVpJTYo,iv:zdvAfrek16EjaMKAaRA3JTjLOO6V9YS+VPbRNthu35E=,tag:7/8ej1O9vxxJXiOkuAlXBg==,type:str]
    username: ENC[AES256_GCM,data:fX4WREA=,iv:tPPlPymkjghJJBWySOl8Vwfi/ZDzfK1Ez7EdGqN1D2E=,tag:WKKuaWCNyTI/PksSYqvunQ==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x05r8tdwj7ruzqffcuamt3v7gnf82ldcmrjq8zd3fnh9593grd8sktr4ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVDZ5UG8rYzlqZXM0Z1RR
            VzJOT2JEMnFXYkplZDdPdE5zY1lXbG0ybkdnCjRqZmlubUlmTklNT0FFaHhLNXU2
            cXgzNzBZZG1qcVVFZnVyb0tPdVFOOHMKLS0tIC9JMkNwN2Fvd3NtR2RPU1Z6UUR5
            THdXV01RNnJJcHl2QXFlUlVUNlA3c28KRB0SpFb0qFuzLh5zo8QRoURH0/AWAwA+
            yqjws8vz3w1wmldytYTuFlqicfHoKR+5MwBRVInVcA76jN2ifa29xw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-18T10:50:15Z"
    mac: ENC[AES256_GCM,data:oVu8ZfBB4GocSJbV4YyWy8mPIP93HjbBSf7CMjYzG4ehfMTUKx6mJIdIewKdEoQY1cVNqKEZ/LGc4uwpqZKgw58fhxWUbD1RdkBnoVkSbbwUdur4hk8twEU6uqU5X2CLQt1WYI+vBvhvgPtVCAXroz83lG5KjHupR6UC8o+Li1k=,iv:CQMv7mnd6CUjlNOQwTWyVF3mRujKGj+8hi2TfnHxqDA=,tag:+8v3PotwEGaK8Hiy6HzYJA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
