apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:f5hYXgNTd2zCN5JU2HJcNi53T9+iVYnNQkAuLOxEEkSCYVZOrR3pzAO3dsRwgY2igsChwyFxlaLbgkDx,iv:V3oUhLBGGtb5xDebuPmTYepuchMouJ7FeADQnZO0/Os=,tag:ZHnBxOE5YO9WjQVCnyjXAA==,type:str]
    username: ENC[AES256_GCM,data:JveoPCc=,iv:CVbeJcdHWTRPA9ZuwKf0bV5EcgnjU+pcTl2AZyi444o=,tag:T+eitdH82qggBRBmMftg2Q==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x05r8tdwj7ruzqffcuamt3v7gnf82ldcmrjq8zd3fnh9593grd8sktr4ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQ0dpUlVJN2x3bnNldzli
            T1MzZjh0ZHBKejgxbWpKODhQVlZhLzFmQWtnClVtSWNKOVhVYWRlYlkrQ2FkMndQ
            dERjcU01RmxneEI5RVErSTZhWjEyalEKLS0tIFNaMFBFbFpwVnNIZ29leCtOc2h4
            RFc3aTEvRmUxQWVUTFhHWTVqWk5Ra1kKa5ehb+Tjkd0E4v8kIOSN35Rn3aNV0NWi
            ISCd+x20IbRUEWgYw/OUxYgLzdWTrxelDRTzlEPKk+ygMcvAfMhJlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-18T11:29:08Z"
    mac: ENC[AES256_GCM,data:CRAV7mq44TbnIYxsNhYvYqc/pRXb1r5riZbUtzgS1icz16XJZY+N8F8bQqN4tCJisDNPoy74DxR3RN5+WleOZnxtYG498LpaixdYEibD7+Ink+Dpd4xeiDmGyVpbi7mjYD69WEYIbrIeN25wM0sBV4eEMAuWeF4yxur/knUPbAY=,iv:/95WC0ATPbXfos6F1dB1dq9H7SeLzTuyN7GUOqanSxs=,tag:0je6WncVEt1/TEhT/Q5iDw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
