---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/litellm.home-operations.com/litellmmodel_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: hermes-3-3b
spec:
  modelName: hermes-3-3b-local
  params:
    model: openai/hermes-3-3b-local
    apiBase: http://hermes-3-3b.ai.svc.cluster.local:8080/v1
    apiKey: none
    additional:
      temperature: 0
  info:
    maxInputTokens: 16384
    maxOutputTokens: 256
    maxTokens: 16384
    mode: chat
    supportsFunctionCalling: true
