---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/litellm.home-operations.com/litellmmodel_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: qwen3-4b
spec:
  modelName: qwen3-4b-local
  params:
    model: openai/qwen3-4b-local
    apiBase: http://qwen3-4b.ai.svc.cluster.local:8080/v1
    apiKey: none
  info:
    maxInputTokens: 131072
    maxTokens: 131072
    mode: chat
