---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/litellm.home-operations.com/litellmmodel_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: qwen3-embedding-0.6b
spec:
  modelName: qwen3-embedding
  params:
    model: openai/qwen3-embedding
    apiBase: http://qwen3-embedding-0-6b.ai.svc.cluster.local:8080/v1
    apiKey: none
  info:
    mode: embedding
