apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:Snu+1Qvo8v9hBcg1F5ES1RZCUNMvoqru+62uyXECmexdBL1VbKlulLpMlz3qxNuTXIxebNU=,iv:guNgcRRjrUob/FVGS+6EaZVNLrqyaR7DGg7uA+RkqNg=,tag:twsqbaPO6qO04ACAFDmobg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFUwRVVBTTBq
        TE1WMGJCaE9IMHFqN21XaTBHdWY3NUFKWVBUNE1ISW1McHQ0UFJTLzM0UVByRy9Q
        SjBDWXVTaXhOVHRtMk96RFVpcmh0T3hmU0JwZnFvOTF2ZVV0OVRoUSsvYko1WXJi
        WWxzbUpkUnVqdGVQZFY5ZTZrRExaTGVrUDFEYWxlR1MvV0c1NFZaVUpVdUYrUUNM
        MHExVVV2M3VHNDlBVlpLb3JJM0tFR3VLbEdkaWRVUXRjcjJRandnc0wwTEliNis5
        ME5IYmU2VzBGeUNEWXZyR0w2Ym1MeU5IWkh3dGU4RHQ5c2lkalEyekpmYXpNUlNH
        QzUwblpCc1VaWW4vampoaU9rNVNqZE83NnZPRFJwUTlVcmZZdEhGZDEzeXEyRjAx
        OC9HU1h1U0llcE50ZlZFTTA1cEd2QzBqSmZUMjlVaFNESXB5QklRWEJHcDJGL3kv
        MFRMa21FbzdsTFc3WnhqbWFmbHhhVlczUjVvT3lQL1JRdzRFQzB3bFAwR3lTNzcr
        S0cyMWlBNm41dUNXV1Y3blIvaWZxVXVJRDlqdzRCU1RvS3FuVTJXNk5PcERlcTli
        TVhXYmNnV0dJelliVDhYQWFTM1pwMVhhVC9pd0xKQlpCMDlTNndPTy9LaWdnWjZr
        TkMwN2NFbzQzTzJjYTN1ZlZVN293M3RaUFE1TURaVk1LT3dwd2M3ZTRwSGJBN1JW
        eXBtekcwMTZhVm1rWkpHTE5TTld3UFNQTkhlVFpLemFNWGVjN1ZPT214dWR5K3BR
        NXNkMDdueWwvK2tQV2k5TG9wRWpyVzdiY21oakU0SUJjZlBVdGVSVFQrZ29kTk1w
        dDAyeFl1dHY1dW11WTJhMms4Njl4WklUdVVSU1F3UWcrRjB6Sy9RVmlzVmhxNytx
        ckV4T3JHVnlEQjRjeU1ocHd3OTdsY0FpYUdyb25lQk5meFJ3YUxIZjZaM0k3NDlX
        WnR3eldERThMQnlyQWVVdHBSNDIzNFNZalJtdkFPOVVncnVWYXU5RXN2eGl0QXNY
        MUEvM0xCRW1nWXRmN1JhcmJmNElhTGhqR3kxMU5ieHNCU2plSkJ5RExtcG83ZHhM
        czFpSGZoZkcwRU1seEx4ZU0yLzEvQ20vRHRxSWVYR3F1MCt2RDFvcGlZeEVvN0dX
        dk1jd1ZVQjhTS2JDVHk2am9HMitzOGZDRW5EbFVya2lMUmNSSVZ2Sm9ZQW1yQWRP
        dnRKaUl1UXp4Z2Q0dVE1ZmNLb0ttTUJTdlhtU3VxclFwcmJnYUtHN1JCT2tJbXlm
        Qi9VZFQrVzYySExLdkhodTZCeWtaMGw0eVpxUWtSRDJob3BQNHpEWFcvcGM2dWxy
        MUpUM3YwZkQ0TGNTTnovdHlyZkd5NUZ2UkFTR2p0UnZKRUgyZjEyN1NMWGtVWVJw
        d2hIYTFtV2NLTHQwVlpyZWdHYTBGT2hGc3NkVW01N3JQQzVlc3QwMEdqdVpWbFQz
        SThOcEFSUkFZc3ZwdGV1bUtXUExpcURsRkZBM00wZGhmSXVxbXk1dndWWFBoQnp6
        SlhOUzFRK3Q3TXJlRC9XaVJUTHV2N052d2IzcmlnekR2eUZ5NkZnN295ekVlc0ZZ
        U2c2WGFobEVEMTJ2Y0FyR0MxWEh5d25vOXZyQUpETFFScVZYMHcveFUzT1loeUtl
        OWJ3OGVCb0kvSDVYSjFxcmFDQU04V3VJbjJybWMyR3VIWTlMOTZ3K0plZW1FTk52
        R1RWejNXeE5lMmd5Yk1HZk5Ub1ZqZG5xT1k2NStENHBpYWJGMElBUVQraitDTUpG
        aCtadEsyeEliNWljdHBLTklOVUFRU0hKZXZyYTRyWUhjTHVPbDdCZ3FwbVVjeXdH
        WEVuaHBiS2lpWlBKQ1duQTVrZHAyakc4VENXYy9KK090M1NrcDVFWjJHbnRwdW13
        UUhiNnpHMGZaMmVRemErSnpNNjE1Z3pjQW5MaEw1VUVlOGlLelp4dGhGTEpKUQpZ
        OXc4SENVZ1puK2pycnVQOVcwSVZ4REIySk0rZFhDMVlRckloMTJmNmcwCi0tLSBr
        Vmk4WnlvSncwOURjVnlWMkxGWkIvQkhLd3NLQjJnbE14cWpQNWdKTC9VCjs1hVkr
        pPqHerr7FII5JMQVfaKfKO82a+n+timkzkBj1ArjwNLNoUgLYjEd9TOaH2l2XaEd
        RDwwfy65oNIY8Tw=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1gqj5utvvc0rs900wzyaen9etl26xpk49f49ask0dlzdrcpt2xkakyl75q49esxh8a342s6pwydt668rxgzr7c9ntfv0lmh9z277x6hcsfceefzx0sy8x2u7t3ltt2x4zpck42t9432axlzeqfgaenc0h82yjnzgqezs3x6jurmetk5z88tpzr2at0pv4pekza7dfnx3n54hgsk6tdprac6jx6r2rxzre8mh5dqgd799hety35ed3v593n0f52fuzqcl2395wzqnj29yhkq05s8vcqqtzv2e0s4aun9tzptny3srhpps7zjghpsdrnchsq8rld8vvmsv9cw7yghnf046e46nq5cp893749q9wu6yeaszznxt8z06uhwlsl7323d98te22pacv3nh8r26n2j696nt6arg8hvgwsf4vey9llsugj925fst8j5gw9wmfktymlrzs3xj82rnq9nrmnxqh4sndveu0txppryscxl9c3d9rxc450qrfh9thakf4zn6aevayfs402vtju63530tzj9lygqmuq6jef663p2as47k897nwgp2g7whnsz60l2yf6ljk33g3nd23wsv02yg33v7ge7mmdqj7kvak8v8p65n72qyk5qkjt2u4rfyxrxpjeagf4eex6qurk3dx0rd7mzvvnksd3ygrq5ymxn02sz75qx0dh6gy2qkteeu3pvhqjpwzkc5m5nz9jcdnevext58d9q4h25qzuv2hlnresdhf89an9j7j83n8zw6whjmyxxajklazcm4y23jglvqaudgphsdtqljuqukx8sye59vqm45kjergga9kp8xs63r5lg2xvh4nta8mvrc5fxc6nvgdcsp38jqytpcvhhdw2l70nydk0dr24t65ad28cnn8kl5u7zze8fvn5wfkav7505dms27wq7wqy9pu3pnhzddtfat98fa9sawwx44k06qvzqqupwxhj3f3kan3ecmpwae2cmysstv4x40jns9scx279m6rjsjm3cv9v9fvvzy6gv6awtsx0nqjvx0x8tqp6q3na5ux6utrkncgev4y2kepsnrfj7e6ygwyxm0c2zalj4lc63eptfzhpzyzpqfvcsg0kax3rvy5n7c3gs9yxft4hvpp5yp2m3ztuawfc7t8uqq6s44vqsfrs3rt0c6n332rqwfkn4fxjuzxfza8uypyzue507ath2mr4x4ts2kv0up6gk7pgvdt53v9fxstktxqpp7965e4gdcg5t4mdrxt6g4tuxsny3pugjcyeda0tqau8w4aj6v2e2w9ada99m6w52aqqva2gs4gnrw92ta4ekgrksszs0qdl7qf0kneqhm4gg2pyx4vkfrfhvcd4cj9wqmyzm5hs03jpgjl43pjyk7883ts3e8y9slewg2pl4gzypm6ta2shrr6f0mk2vtnytpe6vs909w6sq6my4sh66pc9wd35an6097pj4d4nwhemv0s3xq9k5g23jcjxcmuykyn89hzcf3x7ptkayxz2d0fp26g2z3z8szn9nw2m0qf0w26qa925357c6vs28pmkqy8fz82jgt8axglvtq9hycksqcmf2lmyvudej0sfxsu3c25xnk3vqx5vv5a58q03v7f256pce9vvtxtrdsrvv82chya4kqegz55p3d5et3t2j8fvqpt5xerdhz42h2e29n6fp56ylzecsur93jfp6g5gjdz8qqqldeyvf9cwzj3509jc3dnl2sr3nqe6srmhf5fzu30qek73fxq439x4722c6kz0k0cwc2lxsytse4d0kyn7kgtyyp5kglxms9sdxtazfa6f0wxxggg0pxculqlzatcvl07exl7e09wm0kuqg0fqapad8csxn363twn2pey0pqdnxt6t87mwkc4fu42j0cz98wqvsry885wles9pv73djqsudtxc7zkxcr3x85s
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-07T14:41:59Z"
  mac: ENC[AES256_GCM,data:629Z86Qr4744PPFNGBf+ncUftAC5JCbX82ZqoyVLVMcHb7CqsWrA66ArM8JpPN9+iP7omGGQMgowU5+HcxOeChi2RHetGjVEAQ2kxpyUpT1JL4e+tqi+1pCTixXRR1Lp7Ilw0q7KYj/QMrmBtNLjiGfhaSIaLnuuvzF/jMV95AQ=,iv:CrdK6/dWkGa+9lZo02ljDcQwz5vlDb2laSF4dm8Fde4=,tag:zTW28HGNCQxLSGyK8ckHpA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
