---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager-external-secret
  namespace: monitoring
spec:
  target:
    name: alertmanager-secret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        ALERTMANAGER_DISCORD_WEBHOOK_URL: "{{ .ALERTMANAGER_DISCORD_WEBHOOK_URL }}"
        ALERTMANAGER_PUSHOVER_TOKEN: "{{ .ALERTMANAGER_PUSHOVER_TOKEN }}"
        PUSHOVER_USER_KEY: "{{ .PUSHOVER_USER_KEY }}"
  data:
    - secretKey: ALERTMANAGER_DISCORD_WEBHOOK_URL
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: f6f71b22-c696-49a8-a9de-b0cd00e195b6
        property: ALERTMANAGER_DISCORD_WEBHOOK_URL
    - secretKey: ALERTMANAGER_PUSHOVER_TOKEN
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: f6f71b22-c696-49a8-a9de-b0cd00e195b6
        property: ALERTMANAGER_PUSHOVER_TOKEN
    - secretKey: PUSHOVER_USER_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: f6f71b22-c696-49a8-a9de-b0cd00e195b6
        property: PUSHOVER_USER_KEY
