---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager-external-secret
  namespace: monitoring
spec:
  target:
    name: alertmanager-secret
    deletionPolicy: Delete
    template:
      templateFrom:
        - configMap:
            name: alertmanager-config
            namespace: monitoring
            items:
              - key: alertmanager.yaml
  data:
    - secretKey: ALERTMANAGER_DISCORD_WEBHOOK_URL
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: f6f71b22-c696-49a8-a9de-b0cd00e195b6
        property: ALERTMANAGER_DISCORD_WEBHOOK_URL
    - secretKey: ALERTMANAGER_PUSHOVER_TOKEN
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: f6f71b22-c696-49a8-a9de-b0cd00e195b6
        property: ALERTMANAGER_PUSHOVER_TOKEN
    - secretKey: PUSHOVER_USER_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: f6f71b22-c696-49a8-a9de-b0cd00e195b6
        property: PUSHOVER_USER_KEY
