---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ./external-secret.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: alertmanager-config
    files:
      - alertmanager.yaml=./config/alertmanager.yaml
generatorOptions:
  disableNameSuffixHash: true
