---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hermes
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: hermes-secret
    template:
      data:
        DISCORD_ALLOWED_CHANNELS: "{{ .DISCORD_ALLOWED_CHANNELS }}"
        DISCORD_ALLOWED_USERS: "{{ .DISCORD_ALLOWED_USERS }}"
        DISCORD_BOT_TOKEN: "{{ .DISCORD_BOT_TOKEN }}"
        DISCORD_HOME_CHANNEL: "{{ .DISCORD_HOME_CHANNEL }}"
  dataFrom:
    - extract:
        key: hermes
