---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: qbittorrent-exporter
  namespace: monitoring
spec:
  staticConfigs:
    - targets: ['prometheus-qbittorrent-exporter.downloads.svc.cluster.local:8000']
  metricsPath: /metrics
