apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:BWLox4G8FJ/FgAT3QstChZzS3mBZtG7Z,iv:VJQTGRagipiOhnAf0EybmH7OkSez1+3QhbFjf/2G08E=,tag:Ys1ZN5aZ3sK59iMXKe8USQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:Fakw/kCM3biFphU5EVsY7XMeOQuM5hNOkja6UIVwhvJC9z6V,iv:VscIXtSm2ejbQxKs328hP7FHhFCfIzjdSzXa4RF80Kc=,tag:FgRywd79Ays+5jqcncE4kw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:RyFEPYcYLL/P,iv:FoSt5/zI/cPfw8qtZLHJNkTQQYyv+wVLmAg83HoQa3A=,tag:FjCo96gTNoLPGvoIad1bug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x05r8tdwj7ruzqffcuamt3v7gnf82ldcmrjq8zd3fnh9593grd8sktr4ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtd3ZQR3R1QTlQTm1qcVR1
            SEUyOGREUEpXeW1lYVlON210QVBpdzc0bWxVCllNaDFsczQ0b2hEVmJCaVpuRFNx
            QzRLcFVqeHdKVExWSjFNTjIvNXNFTmsKLS0tIGFNOU1RZGhobnFWaXlrU0dMWG55
            VmhRQjdKK1d1UE1oeUh3ZVQ3SGRqNVkKD5mIqaCtlQdzK2QlJlE649+ZLRkfmdtG
            Z1Pc6jVjZ4CVOggGTINVGcHIMRVt9YCVtIThHlCNjcxiqTLL0YpQuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-18T11:18:58Z"
    mac: ENC[AES256_GCM,data:sUZ7ff2AeusfzZOS3LTOz39zbK0+z3oSJZyqxzImEyG8pGfY2bPmqXkEZA4slTcGpnDEHIG5A8pP8E/f7S77WrjgemW9vzQFrpmoH9phox4lhJ4cjIvQNcyg5eDMIJbaGnS6wnsUBtiZGFgqG++3HeagRE3Qrla9YjmikX8fukY=,iv:QCwmioHQqhptLIq1mRd/oLOkwqw/N6W/KQmoGtt7L8A=,tag:DiL+24m8AlfigGZIfpAnUg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
