---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  namespace: storage
  name: longhorn-recurring-jobs
spec:
  targetNamespace: storage
  releaseName: longhorn-recurring-jobs
  upgrade:
    force: true # In case a StorageClass needs updating
  dependsOn:
    - name: longhorn
      namespace: storage
  timeout: 120s
  chart:
    spec:
      chart: longhorn-recurring-jobs
      version: "5.0.2"
      sourceRef:
        kind: HelmRepository
        name: tyzbit
        namespace: flux-system
  interval: 2m0s
  values:
    minuteStep: 5
    hourStep: 2
    createStorageClasses: true
    storageclass:
      allowVolumeExpansion: true
      reclaimPolicy: Retain
    parameters:
      replicaAutoBalance: best-effort
      dataLocality: best-effort
      numberOfReplicas: "3"
      staleReplicaTimeout: "30"
    groups:
      "database":
        snapshot:
          - interval: 10m
            retain: 6
        backup:
          - interval: 24h
            retain: 7
      "config":
        snapshot:
          - interval: 10m
            retain: 6
        backup:
          - interval: 24h
            retain: 7
      "Snapshot":
        options:
          storageclass:
            reclaimPolicy: Delete
          parameters:
            numberOfReplicas: "1"
            dataLocality: disabled
