---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage
resources:
  - ./helmrelease.yaml
labels:
  - pairs:
      app.kubernetes.io/name: longhorn-recurring-jobs
      app.kubernetes.io/instance: longhorn-recurring-jobs
      app.kubernetes.io/part-of: longhorn-recurring-jobs
