---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: downloads-gateway-vpnconfig-external-secret
  namespace: vpn
spec:
  target:
    name: downloads-gateway-vpnconfig-secret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        WIREGUARD_PRIVATE_KEY: |-
          {{ .private_key }}
        WIREGUARD_PUBLIC_KEY: |-
          {{ .public_key }}
        WIREGUARD_ADDRESSES: |-
          {{ .addresses }}
        VPN_ENDPOINT_IP: |-
          {{ .endpoint_ip }}
        SERVER_COUNTRIES: |-
          {{ .server_countries }}
  data:
    - secretKey: private_key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 896f6562-1925-421b-b4c8-b050011df4c1
        property: private_key
    - secretKey: public_key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 896f6562-1925-421b-b4c8-b050011df4c1
        property: public_key
    - secretKey: addresses
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 896f6562-1925-421b-b4c8-b050011df4c1
        property: addresses
    - secretKey: endpoint_ip
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 896f6562-1925-421b-b4c8-b050011df4c1
        property: endpoint_ip
    - secretKey: server_countries
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 896f6562-1925-421b-b4c8-b050011df4c1
        property: server_countries
