---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: downloads-gateway
  namespace: vpn
spec:
  interval: 30m
  chart:
    spec:
      chart: pod-gateway
      version: 6.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: angelnu
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/angelnu/pod-gateway
      tag: v1.10.0@sha256:d728eac85f750b37c96a0dafd038561ea4b8035857802be1128ea9b19c61e181
    podAnnotations:
      reloader.stakater.com/auto: "true"
    DNS: 172.16.1.1
    service:
      vpn:
        enabled: true
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 10.10.1.231
        externalTrafficPolicy: Cluster
        ports:
          shadowsocks:
            enabled: true
            port: 8388
    addons:
      vpn:
        enabled: true
        type: gluetun
        gluetun:
          image:
            repository: ghcr.io/qdm12/gluetun
            tag: v3.37.0@sha256:ba9688ff9abaf73bbc0b257be547b51a097ca74324fedddeeb709732c2692eef
        env:
          - name: VPN_SERVICE_PROVIDER
            value: mullvad
          - name: VPN_TYPE
            value: wireguard
          - name: VPN_INTERFACE
            value: wg0
          - name: FIREWALL
            value: "off"
          - name: DOT
            value: "off"
          - name: SHADOWSOCKS
            value: "on"
          - name: SHADOWSOCKS_PASSWORD
            value: ${SECRET_VPN_SHADOWSOCKS_PASSWORD}
        envFrom:
          - secretRef:
              name: downloads-gateway-vpnconfig-secret
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
      netshoot:
        enabled: true
    publicPorts:
      - IP: 10
        hostname: qbittorrent-0
        ports:
          - port: ${SECRET_VPN_FORWARDED_PORT_1}
            type: udp
          - port: ${SECRET_VPN_FORWARDED_PORT_1}
            type: tcp
    routed_namespaces:
      - downloads
    settings:
      NOT_ROUTED_TO_GATEWAY_CIDRS: 10.0.0.0/8 192.168.0.0/16
      VPN_BLOCK_OTHER_TRAFFIC: true
      VPN_INTERFACE: wg0
      VPN_LOCAL_CIDRS: 10.0.0.0/8 192.168.0.0/16
      VPN_TRAFFIC_PORT: "51820"
      VXLAN_ID: 43
      VXLAN_IP_NETWORK: 172.16.1
    webhook:
      gatewayAnnotation: set-gateway-vpn
      gatewayDefault: false
      gatewayLabel: set-gateway-vpn
      image:
        repository: ghcr.io/angelnu/gateway-admision-controller
        tag: v3.10.0
