---
apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-config
data:
  settings.yml: |
    ---
    use_default_settings: true

    general:
      instance_name: SearXNG

    server:
      image_proxy: false
      limiter: false
      method: GET
      public_instance: false

    search:
      autocomplete: ""
      favicon_resolver: ""
      formats:
        - html
        - json
