---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cloudnative-pg
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: cloudnative-pg
      app.kubernetes.io/name: cloudnative-pg
  podMetricsEndpoints:
    - port: metrics
