---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: actions-runner
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: actions-runner-secret
  data:
    - secretKey: github_app_id
      remoteRef:
        key: actions-runner
        property: github_app_id
    - secretKey: github_app_installation_id
      remoteRef:
        key: actions-runner
        property: github_app_installation_id
    - secretKey: github_app_private_key
      remoteRef:
        key: actions-runner
        property: github_app_private_key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pr-reviewer-litellm
spec:
  secretStoreRef:
    kind: SecretStore
    name: pr-reviewer-litellm
  target:
    name: pr-reviewer-litellm
  data:
    - secretKey: key
      remoteRef:
        key: pr-reviewer-litellm
        property: key
