---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: paperless-external-secret
  namespace: default
spec:
  target:
    name: paperless-secret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        PAPERLESS_DBENGINE: postgresql
        PAPERLESS_DBPORT: "5432"
        PAPERLESS_DBNAME: &dbName paperless
        PAPERLESS_DBHOST: &dbHost postgres-rw.database.svc.cluster.local
        PAPERLESS_DBUSER: &dbUser "{{ .POSTGRES_USER }}"
        PAPERLESS_DBPASS: &dbPass "{{ .POSTGRES_PASS }}"
        PAPERLESS_ADMIN_USER: "{{ .PAPERLESS_ADMIN_USER }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ .PAPERLESS_ADMIN_PASSWORD }}"
        PAPERLESS_SECRET_KEY: "{{ .PAPERLESS_SECRET_KEY }}"
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  data:
    - secretKey: PAPERLESS_ADMIN_USER
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b578e02a-f232-4dac-a73c-b06b00f65467
        property: username
    - secretKey: PAPERLESS_ADMIN_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b578e02a-f232-4dac-a73c-b06b00f65467
        property: password
    - secretKey: POSTGRES_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: b0f64f2d-7a43-4ac2-9b6d-b02e01525324
        property: paperless_pg_user
    - secretKey: POSTGRES_PASS
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: b0f64f2d-7a43-4ac2-9b6d-b02e01525324
        property: paperless_pg_pass
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b0f64f2d-7a43-4ac2-9b6d-b02e01525324
        property: username
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b0f64f2d-7a43-4ac2-9b6d-b02e01525324
        property: password
