---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paperless #redeploy
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    initContainers:
      01-init-db:
        image: ghcr.io/onedr0p/postgres-init:14.9
        imagePullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: paperless-secret
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/paperless-ngx/paperless-ngx
      tag: 1.17.4
    envFrom:
      - secretRef:
          name: paperless-secret
      - configMapRef:
          name: paperless-configmap
    service:
      main:
        ports:
          http:
            port: 8000
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/icon: "arcticons:paperless"
        hosts:
          - host: &host "paperless.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host
    persistence:
      nas-consume:
        enabled: true
        mountPath: /data/nas/consume
        type: nfs
        server: ${SECRET_NAS_IP}
        path: /mnt/rpool/paperless/consume
      nas-export:
        enabled: true
        mountPath: /data/nas/export
        type: nfs
        server: ${SECRET_NAS_IP}
        path: /mnt/rpool/paperless/export
    resources:
      requests:
        cpu: 15m
        memory: 1000M
      limits:
        memory: 1800M
    volumeClaimTemplates:
      - name: data
        mountPath: /data/local
        accessMode: ReadWriteOnce
        size: 15Gi
        storageClass: longhorn-config
