---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-policy-control
rules:
- apiGroups:
  - ""
  - networking.k8s.io
  resources:
  - pods
  - ingresses
  - configmap
  verbs:
  - create
  - update
  - delete
  - patch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-policy-control
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-policy-control
subjects:
- kind: ServiceAccount
  name: k8s-policy-control
  namespace: system
