---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: longhorn-external-secret
  namespace: storage
spec:
  target:
    name: longhorn-secret
    deletionPolicy: Delete
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      type: Opaque
      data:
        AWS_ACCESS_KEY_ID: |-
          {{ .access_key_id }}
        AWS_SECRET_ACCESS_KEY: |-
          {{ .secret_access_key }}
        AWS_ENDPOINTS: |-
          https://${SECRET_CLOUDFLARE_ACCOUNT_ID}.r2.cloudflarestorage.com
  data:
    - secretKey: access_key_id
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: b34700f1-ddd8-4a42-b2ec-b03b00f76592
        property: access_key_id
    - secretKey: secret_access_key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: b34700f1-ddd8-4a42-b2ec-b03b00f76592
        property: secret_access_key
