---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns-public
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-external-dns
  path: ./kubernetes/apps/networking/external-dns-public/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
