---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: actual
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: actual-secret
    template:
      data:
        KANIDM_CLIENT_ID: "{{ .KANIDM_CLIENT_ID }}"
        KANIDM_CLIENT_SECRET: "{{ .KANIDM_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: actual
