apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: actions-runners
components:
  - ../../components/sops
resources:
  - ./namespace.yaml
  - ./pr-reviewer/ks.yaml
  - ./network-policies/ks.yaml
