---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cilium-policy.yaml
  - ./dockerhub-rate-limit.yaml
  - ./kopiur-snapshot-pending.yaml
  - ./oom-killed.yaml
  - ./zfs-unexpected-pool-state.yaml
