apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:sEOwb1HtPNuwd+EoEIJoj1Z/9zRgnBXsPMhT+2PrgvHwMFoO,iv:ZEiEncS5CB450p9AabO8pIMSCaDyH1JS8J4eOF1d58k=,tag:z1uGagF+kaHmrHxEopjfUA==,type:str]
    credentials.json: ENC[AES256_GCM,data:PHYvd5pNcazZvEx41zAh87yCR4xennh5P8XMIIJkeT+dt+fPiFHLDatE5KHvpw8lSQMoK6i2JfBZbOww6uMYhMyne2W3nZLKNk4G7jiDvSpdNgvQ3qJORMjz2uBKgmG7fR5NC0j6Vg29Ve1VcGclm2zKPmxOv25MKVW+jyNV4fGQhFlBXeVg37e8vWFYMCWGhBn/rGdRraggHf1vZk8fsQ2KirBQW/q6dN735gbusQ==,iv:sYtF7MdIliwxdf19EXFdaWSqpKrFM4zhwXMKXlM809o=,tag:VNfXHjUF4NxDocEoijg4MQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x05r8tdwj7ruzqffcuamt3v7gnf82ldcmrjq8zd3fnh9593grd8sktr4ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzeHo2a1VLUnBWQmdJaWM0
            NFFjc29Rb3BUK1NQc242N3FYY0tCUU9jL3hFCmR3SUo1U2ozRzhiOXFLQkQ0bFNa
            dk04a1pFclZNMk1tRUVIM3ZGbEpRS0UKLS0tIEFHREdXWXZjYzZSMU1EdlU1T0x2
            clJ6RVdyeGxVYURKU1dQR3QvbGhJY1kK2AUNOmEs7hPm/tP2AaQqouXv2v1Ijfk+
            fEJOsbyc1y9kh/Hpzm9iZJqjo3vs8Bp0InF9jLmhDX8eWLoS41GU1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-18T12:11:16Z"
    mac: ENC[AES256_GCM,data:q5XpBBx+qaUouN076ZZlo4+Uw4K3W9NDJYNUuSTvXKYb/VINnxwvLj3mgpV1DWQ82Bb99Njj/k1NWbYYiLnaKf4zlAQaBqc5jrGszPCq5uU0lchfhms4yLXC74LWlpWqVZfib2MquhDW3tyv3NesHelSOFl8rg5r8ZdoU7T+sT0=,iv:TMlKgaTtryp9rUDDtZymD4czYppmm82oeuSDfbtNRbA=,tag:fiyEf4HIOVkSPwR4vTnmlQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
