---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./hermes-3-3b.yaml
  - ./qwen3-embedding-0.6b.yaml
  - ./qwen3-4b.yaml
configMapGenerator:
  - name: hermes-3-3b-chat-template
    files:
      - hermes-3-tool-use.jinja=./hermes-3-tool-use.jinja
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
