---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gmailctl
  namespace: system
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/aumer-amr/gmailctl
      tag: sha-b6a1d17
    env:
      TZ: "${TIMEZONE}"
      CONFIG_DIR: /config
      DATA_DIR: /data
      DEBUG: "true"
    persistence:
      config:
        enabled: true
        type: secret
        name: gmailctl-config-secret
        mountPath: /config
        readOnly: false
      data:
        enabled: true
        type: secret
        name: gmailctl-data-secret
        mountPath: /data
        readOnly: false
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/enable: "false"
        hosts:
          - host: &host "gmailctl.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    resources:
      requests:
        cpu: 100m
        memory: 128M
    service:
      main:
        ports:
          http:
            port: 3000
