---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system
resources:
  - ./config.secret.sops.yaml
  - ./data.secret.sops.yaml
  - ./helmrelease.yaml
labels:
  - pairs:
      app.kubernetes.io/name: gmailctl
      app.kubernetes.io/instance: gmailctl
