---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sendspin
spec:
  dependsOn:
    - name: network-policies
    - name: coredns
      namespace: kube-system
    - name: music-assistant
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 1h
  path: ./kubernetes/apps/home/sendspin/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: home
  wait: false
