---
apiVersion: mariadb.mmontes.io/v1alpha1
kind: Database
metadata:
  name: monica
spec:
  mariaDbRef:
    name: mariadb
  characterSet: utf8
  collate: utf8_general_ci
---
apiVersion: mariadb.mmontes.io/v1alpha1
kind: User
metadata:
  name: monica
spec:
  mariaDbRef:
    name: mariadb
  passwordSecretKeyRef:
    name: monica-secret
    key: DB_PASSWORD
  maxUserConnections: 20
---
apiVersion: mariadb.mmontes.io/v1alpha1
kind: Grant
metadata:
  name: monica
spec:
  mariaDbRef:
    name: mariadb
  privileges:
    - "ALL"
  database: "*"
  table: "*"
  username: monica
