---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: monica-external-secret
  namespace: default
spec:
  target:
    name: monica-secret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        DB_PASSWORD: "{{ .db_password }}"
        MONICA_APP_KEY: "{{ .monica_app_key }}"
        MAIL_USERNAME: "{{ .mail_username }}"
        MAIL_PASSWORD: "{{ .mail_password }}"
        MAIL_FROM_ADDRESS: "{{ .mail_from_address }}"
        AWS_ACCESS_KEY_ID: "{{ .aws_access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ .aws_secret_access_key }}"
  data:
    - secretKey: db_password
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: bc4d25ca-a1f5-4e08-92ed-b0a900b61e1d
        property: db_password
    - secretKey: monica_app_key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: bc4d25ca-a1f5-4e08-92ed-b0a900b61e1d
        property: monica_app_key
    - secretKey: mail_username
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: bc4d25ca-a1f5-4e08-92ed-b0a900b61e1d
        property: mail_username
    - secretKey: mail_password
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: bc4d25ca-a1f5-4e08-92ed-b0a900b61e1d
        property: mail_password
    - secretKey: mail_from_address
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: bc4d25ca-a1f5-4e08-92ed-b0a900b61e1d
        property: mail_from_address
    - secretKey: aws_access_key_id
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: bc4d25ca-a1f5-4e08-92ed-b0a900b61e1d
        property: aws_access_key_id
    - secretKey: aws_secret_access_key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: bc4d25ca-a1f5-4e08-92ed-b0a900b61e1d
        property: aws_secret_access_key

