---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: influxdb-external-secret
  namespace: database
spec:
  target:
    name: influxdb-secret
    deletionPolicy: Delete
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      type: Opaque
      data:
        admin-username: |-
          {{ .admin_username }}
        admin-password: |-
          {{ .admin_password }}
        admin-token: |-
          {{ .admin_token }}
  data:
    - secretKey: admin_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: c3c6b429-ef4d-4b6d-b63e-b03500d9ccc9
        property: admin-token
    - secretKey: admin_username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: c3c6b429-ef4d-4b6d-b63e-b03500d9ccc9
        property: username
    - secretKey: admin_password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: c3c6b429-ef4d-4b6d-b63e-b03500d9ccc9
        property: password
