---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: system
spec:
  interval: 30m
  chart:
    spec:
      chart: kyverno
      version: 3.3.4
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
  values:
    crds:
      install: true
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
    grafana:
      enabled: true
      annotations:
        grafana_folder: Kyverno
    backgroundController:
      resources:
        requests:
          cpu: 15m
          memory: 249M
        limits:
          memory: 249M
      serviceMonitor:
        enabled: true
      rbac:
        clusterRole:
          extraResources:
            - apiGroups:
                - ""
                - networking.k8s.io
              resources:
                - pods
                - ingresses
                - kustomization
              verbs:
                - create
                - update
                - patch
                - delete
                - get
                - list
    cleanupController:
      serviceMonitor:
        enabled: true
    reportsController:
      serviceMonitor:
        enabled: true
    admissionController:
      replicas: 3
      serviceMonitor:
        enabled: true
      rbac:
        clusterRole:
          extraResources:
            - apiGroups:
                - ""
                - networking.k8s.io
              resources:
                - pods
                - ingresses
                - kustomization
              verbs:
                - create
                - update
                - delete
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/instance: kyverno
              app.kubernetes.io/component: kyverno
