---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
  - ./helmrelease.yaml
labels:
  - pairs:
      app.kubernetes.io/name: plane
      app.kubernetes.io/instance: plane
