---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/alertmanagerconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager
spec:
  route:
    groupBy: ["alertname", "job"]
    groupInterval: 10m
    groupWait: 1m
    receiver: pushover
    repeatInterval: 12h
    routes:
      - receiver: "null"
        matchers:
          - name: alertname
            value: InfoInhibitor
            matchType: =
          - name: alertname
            value: Watchdog
            matchType: =
      - receiver: discord
        matchers:
          - name: severity
            value: critical
            matchType: =
  inhibitRules:
    - equal: ["alertname", "namespace"]
      sourceMatch:
        - name: severity
          value: critical
          matchType: =
      targetMatch:
        - name: severity
          value: warning
          matchType: =
  receivers:
    - name: "null"
    - name: discord
      discordConfigs:
        - apiURL: ${DISCORD_WEBHOOK_URL}
          title: |-
            [{{ .Status | toUpper }}:{{ if eq .Status "firing" }}{{ .Alerts.Firing | len }}{{ else }}{{ .Alerts.Resolved | len }}{{ end }}]
          message: |-
            {{- range .Alerts }}
              **{{ .Labels.alertname }} {{ if ne .Labels.severity "" }}({{ .Labels.severity | title }}){{ end }} **
              {{- if ne .Annotations.description "" }}
                **Description:** {{ .Annotations.description }}
              {{- else if ne .Annotations.summary "" }}
                **Summary:** {{ .Annotations.summary }}
              {{- else if ne .Annotations.message "" }}
                **Message:** {{ .Annotations.message }}
              {{- else }}
                **Description:** N/A
              {{- end }}
            {{- end }}
