---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app gatus-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      gatus-operator:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/aumer-amr/gatus-operator
              tag: pr-2@sha256:a1b03dcc0a5bb81454afb12876709f3e5446cdb16b90c8c648df749efbe6b035
              pullPolicy: Always
            resources:
              requests:
                cpu: 5m
                memory: 10M
              limits:
                memory: 64M
            env:
              CONFIG_PATH: &configPath /config/defaults.yaml
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: 8081
                  failureThreshold: 30
                  periodSeconds: 10
    service:
      app:
        controller: *app
        ports:
          http:
            port: 8081
    serviceAccount:
      name: *app
    persistence:
      config:
        type: configMap
        name: gatus-endpoint-defaults
        globalMounts:
          - path: *configPath
            subPath: defaults.yaml
            readOnly: true
