---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: rook-ceph
  values:
    csi:
      cephFSKernelMountOptions: ms_mode=prefer-crc
      cephfsPodLabels: platform.home.arpa/tier=0
      enableLiveness: true
      rbdPodLabels: platform.home.arpa/tier=0
      serviceMonitor:
        enabled: true
    image:
      repository: ghcr.io/rook/ceph
    monitoring:
      enabled: true
    resources:
      requests:
        cpu: 100m # unchangable
        memory: 128Mi # unchangable
      limits: {}
