---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ceph-csi-drivers
spec:
  chartRef:
    kind: OCIRepository
    name: ceph-csi-drivers
  interval: 1h
  postRenderers:
    - kustomize:
        patches:
          - target:
              group: csi.ceph.io
              version: v1
              kind: Driver
            patch: |-
              - op: add
                path: /spec/controllerPlugin/labels
                value:
                  platform.home.arpa/tier: "0"
  values:
    operatorConfig:
      namespace: rook-ceph
      driverSpecDefaults:
        clusterName: rook-ceph
        imageSet:
          name: rook-csi-operator-image-set-configmap
        log:
          rotation:
            enabled: false
        controllerPlugin:
          hostNetwork: true
          priorityClassName: system-cluster-critical
          deploymentStrategy:
            type: Recreate
          replicas: 2
        nodePlugin:
          labels:
            platform.home.arpa/tier: "0"
          priorityClassName: system-node-critical
          updateStrategy:
            type: RollingUpdate
    drivers:
      rbd:
        enabled: true
        name: rook-ceph.rbd.csi.ceph.com
        grpcTimeout: 150
        snapshotPolicy: volumeGroupSnapshot
        log:
          rotation:
            enabled: false
        controllerPlugin:
          hostNetwork: true
          replicas: 2
          resources:
            attacher:
              limits:
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 128Mi
            omapGenerator:
              limits:
                memory: 1Gi
              requests:
                cpu: 250m
                memory: 512Mi
            plugin:
              limits:
                memory: 1Gi
              requests:
                memory: 512Mi
            provisioner:
              limits:
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 128Mi
            resizer:
              limits:
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 128Mi
            snapshotter:
              limits:
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 128Mi
        nodePlugin:
          resources:
            plugin:
              limits:
                memory: 1Gi
              requests:
                cpu: 250m
                memory: 512Mi
            registrar:
              limits:
                memory: 256Mi
              requests:
                cpu: 50m
                memory: 128Mi
      cephfs:
        enabled: true
        name: rook-ceph.cephfs.csi.ceph.com
        snapshotPolicy: volumeGroupSnapshot
        grpcTimeout: 150
        log:
          rotation:
            enabled: false
        controllerPlugin:
          hostNetwork: true
          replicas: 2
          resources:
            attacher:
              limits:
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 128Mi
            plugin:
              limits:
                memory: 1Gi
              requests:
                cpu: 250m
                memory: 512Mi
            provisioner:
              limits:
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 128Mi
            resizer:
              limits:
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 128Mi
            snapshotter:
              limits:
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 128Mi
        nodePlugin:
          resources:
            plugin:
              limits:
                memory: 1Gi
              requests:
                cpu: 250m
                memory: 512Mi
            registrar:
              limits:
                memory: 256Mi
              requests:
                cpu: 50m
                memory: 128Mi
      nfs:
        enabled: false
        name: rook-ceph.nfs.csi.ceph.com
      nvmeof:
        enabled: false
        name: rook-ceph.nvmeof.csi.ceph.com
