# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:qPLVibeXNSZ2+REF8H7RLTGpV7d9q52X3fjIC78RzszSEDgcz0NX5A==,iv:dnZDi0FyUEGZhVhxIEFMibGLaHzqwU16C/igvVdG2zc=,tag:F6RrXbeP/Bq/dR8k941oZw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age17hf2h7uc36snm6hta9l93duhyx6h4q7q8lt9fa89uu67jnajrpts24v5w2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVmE2S2lzcWtqOHZMeExt
        OEEzOUI1bG0vSXlLdmg5VExCTlFWaVFPSUE0CkFWaGNIbWF3V2dZb3hZY1YvOHpm
        V3ZmQ0liNUQ2M0JmMzR0SGdSdnUvVGsKLS0tIDc5OW5OL2Vhem1mVTRzaW4vU3k1
        OWRMbGVKNk9sZElnb01EVHR2QWN6Q1EKWqDVxG87jPHMxHi5xUKHeYTbtNNZAtPl
        uVBpetzcuNiBXKzcBSyOXP9qyXmx4AEnz5Vju+VSne/MnAW6iL4plA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-11T17:27:21Z"
  mac: ENC[AES256_GCM,data:Wn7wC/uWLz/DgebVZABhj8OPNw4pYDSfgDtNcAT1avpEaNLB+Ojb4pYlYWDztKHIiAGkPQ4b6VKz/FWvjxLxx4tYIGwPm/fyIWNnD96Cfnv9IeS/Y5xTsDGR/eY2GE/0nRhGXgTce7u2VNKbQ1qhoLOZ7dvX4dVIh7njJwWbjUQ=,iv:/pJnjYcscvqynvfqpTqLXuzlZ4ecGHRBnQitB3xOZ5c=,tag:cB7DjYqj4E8p1RO/K2Ctrw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
