---
apiVersion: gatus.io/v1alpha1
kind: Gatus
metadata:
  name: &name echo-server
  namespace: network
spec:
  endpoint:
    name: *name
    group: external
    ui:
      hide-url: true
      hide-hostname: true
    url: https://echo-server.${SECRET_DOMAIN}
    interval: 1m
