---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: external-service-greenbone
  namespace: networking
  annotations:
    hajimari.io/appName: greenbone
    hajimari.io/icon: game-icons:dinosaur-rex
    hajimari.io/group: networking
spec:
  ingressClassName: internal
  rules:
    - host: &host greenbone.${SECRET_DOMAIN}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: external-service-greenbone
                port:
                  number: 9392
  tls:
    - hosts:
        - *host
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-service-greenbone
  namespace: networking
subsets:
  - addresses:
      - ip: ${SECRET_GREENBONE_IP}
    ports:
      - name: http
        port: 9392
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: external-service-greenbone
  namespace: networking
spec:
  ports:
    - name: http
      port: 9392
  type: ClusterIP
