---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: external-service-maltrail
  namespace: networking
  annotations:
    hajimari.io/appName: maltrail
    hajimari.io/icon: uil:medium-m
    hajimari.io/group: networking
spec:
  ingressClassName: internal
  rules:
    - host: &host maltrail.${SECRET_DOMAIN}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: external-service-maltrail
                port:
                  number: 8338
  tls:
    - hosts:
        - *host
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-service-maltrail
  namespace: networking
subsets:
  - addresses:
      - ip: ${SECRET_MALTRAIL_IP}
    ports:
      - name: http
        port: 8338
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: external-service-maltrail
  namespace: networking
spec:
  ports:
    - name: http
      port: 8338
  type: ClusterIP
