# curl -u user:password -d "Hello, from the CLI" "https://ntfy.example.com/test"
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ntfy
  namespace: comms
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: kyverno
      namespace: system
  values:
    controller:
      type: statefulset
    image:
      repository: docker.io/binwiederhier/ntfy
      tag: latest
    env:
      TZ: "${TIMEZONE}"
      NTFY_UPSTREAM_BASE_URL: https://ntfy.sh
      NTFY_BEHIND_PROXY: true
      NTFY_BASE_URL: "https://ntfy.${PUBLIC_DOMAIN}"
      NTFY_LISTEN_HTTP: ":8080"
    command: ["ntfy", "serve"]
    persistence:
      data:
        size: 512Mi
        storageClass: longhorn
        accessMode: ReadWriteOnce
        mountPath: /ntfy
    service:
      main:
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "arcticons:ntfy"
        hosts:
          - host: &host "ntfy.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: &uid 7652
      runAsGroup: *uid
      fsGroup: *uid
      fsGroupChangePolicy: Always
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        memory: 150Mi
