---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: paperless-secret
    template:
      data:
        PAPERLESS_REDIS: 'redis://default:{{ .VALKEY_PASSWORD | urlquery | replace "+" "%20" }}@paperless-valkey.administration.svc.cluster.local:6379/0'
        PAPERLESS_SECRET_KEY: "{{ .PAPERLESS_SECRET_KEY }}"
        PAPERLESS_SOCIALACCOUNT_PROVIDERS: >-
          {"openid_connect":{"APPS":[{"provider_id":"kanidm","name":"Kanidm","client_id":"{{ .KANIDM_CLIENT_ID }}","secret":"{{ .KANIDM_CLIENT_SECRET }}","settings":{"oauth_pkce_enabled":true,"server_url":"https://idm.${SECRET_DOMAIN}/oauth2/openid/paperless/.well-known/openid-configuration","token_auth_method":"client_secret_basic"}}]}}
  dataFrom:
    - extract:
        key: paperless
