---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../../../components/cnpg
  - ../../../../components/valkey
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./httproute.yaml
  - ./networkpolicy.yaml
  - ./ocirepository.yaml
patches:
  - target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      name: .*-valkey
    patch: |-
      - op: replace
        path: /spec/values/dataStorage/enabled
        value: true
      - op: add
        path: /spec/values/dataStorage/requestedSize
        value: 1Gi
      - op: add
        path: /spec/values/dataStorage/className
        value: ceph-block
      - op: add
        path: /spec/values/dataStorage/keepPvc
        value: true
      - op: replace
        path: /spec/values/valkeyConfig
        value: |-
          maxmemory 192mb
          maxmemory-policy noeviction
          appendonly yes
          appendfsync everysec
