---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gatus-external-secret
  namespace: monitoring
spec:
  target:
    name: gatus-secret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        DISCORD_WEBHOOK_URL: "{{ .DISCORD_WEBHOOK_URL }}"
        INIT_POSTGRES_DBNAME: gatus
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  data:
    - secretKey: DISCORD_WEBHOOK_URL
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: f3919fab-2007-4014-8fc4-b053013ecb61
        property: discord_webhook
    - secretKey: POSTGRES_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: b0f64f2d-7a43-4ac2-9b6d-b02e01525324
        property: gatus_pg_user
    - secretKey: POSTGRES_PASS
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: b0f64f2d-7a43-4ac2-9b6d-b02e01525324
        property: gatus_pg_pass
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b0f64f2d-7a43-4ac2-9b6d-b02e01525324
        property: password
