---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-authelia
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-external-secrets-bitwarden
    - name: cluster-apps-lldap
    - name: cluster-apps-longhorn
    - name: cluster-apps-nginx-external
  path: ./kubernetes/apps/system/authelia/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
