---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ext-postgres-operator
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: ext-postgres-operator
    template:
      engineVersion: v2
      data:
        POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        POSTGRES_USER: "{{ .username }}"
        POSTGRES_PASS: "{{ .password }}"
        POSTGRES_DEFAULT_DATABASE: postgres
        POSTGRES_URI_ARGS: ""
        POSTGRES_CLOUD_PROVIDER: ""
        POSTGRES_INSTANCE: postgres16
        KEEP_SECRET_NAME: "true"
  dataFrom:
    - extract:
        key: postgres
