---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ext-postgres-operator-external-secret
  namespace: database
spec:
  target:
    name: ext-postgres-operator-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        POSTGRES_USER: "{{ .username }}"
        POSTGRES_PASS: "{{ .password }}"
        POSTGRES_DEFAULT_DATABASE: postgres
        POSTGRES_URI_ARGS: ""
        POSTGRES_CLOUD_PROVIDER: ""
  data:
    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b0f64f2d-7a43-4ac2-9b6d-b02e01525324
        property: username
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b0f64f2d-7a43-4ac2-9b6d-b02e01525324
        property: password
