---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ext-postgres-operator
  namespace: database
spec:
  interval: 30m
  chart:
    spec:
      chart: ext-postgres-operator
      version: 1.2.3
      sourceRef:
        kind: HelmRepository
        name: ext-postgres-operator
        namespace: flux-system
  values:
    podAnnotations:
      reloader.stakater.com/auto: "true"
    existingSecret: ext-postgres-operator-secret
    resources:
      requests:
        cpu: 10m
        memory: 64M
      limits:
        memory: 100M
