---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-movies
  namespace: downloads
spec:
  storageClassName: nas-movies
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-series
  namespace: downloads
spec:
  storageClassName: nas-series
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-cache
  namespace: downloads
spec:
  storageClassName: nas-tdarr-cache
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
