---
name: "Labeler"

on:
  workflow_dispatch:
  pull_request_target:
    branches: ["main"]

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    steps:
      - name: Labeler
        uses: actions/labeler@v5
        with:
          configuration-path: .github/labeler.yaml
