---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tdarr-node-cpu
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: daemonset
    image:
      repository: ghcr.io/haveagitgat/tdarr_node
      tag: 2.00.25
    env:
      TZ: ${TIMEZONE}
      PUID: "1000"
      PGID: "1000"
      serverIP: tdarr.downloads.svc.cluster.local
      serverPort: 8266
      ffmpegPath: "/usr/local/bin/ffmpeg"
      nodeName:
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
    service:
      main:
        enabled: false
        ports:
          enabled: false
          http:
            port: 8265
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    persistence:
      movies:
        enabled: true
        type: nfs
        server: ${SECRET_NAS_IP}
        path: /mnt/rpool/media/movies
        mountPath: /media/movies
      series:
        enabled: true
        type: nfs
        server: ${SECRET_NAS_IP}
        path: /mnt/rpool/media/series
        mountPath: /media/series
      temp:
        enabled: true
        type: nfs
        server: ${SECRET_NAS_IP}
        path: /mnt/rpool/media/tdarr
        mountPath: /temp
    podSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
      capabilities:
        add:
          - CHOWN
      supplementalGroups:
        - 44
        - 105
    resources:
      requests:
        cpu: 15m
        memory: 350M
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: intel.feature.node.kubernetes.io/gpu
                operator: DoesNotExist
              topologyKey: kubernetes.io/hostname
