---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-webui
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: open-webui-secret
    template:
      data:
        OAUTH_CLIENT_ID: "{{ .KANIDM_CLIENT_ID }}"
        OAUTH_CLIENT_SECRET: "{{ .KANIDM_CLIENT_SECRET }}"
        REDIS_URL: 'redis://default:{{ .VALKEY_PASSWORD | urlquery | replace "+" "%20" }}@open-webui-valkey.ai.svc.cluster.local:6379/0'
        WEBSOCKET_REDIS_URL: 'redis://default:{{ .VALKEY_PASSWORD | urlquery | replace "+" "%20" }}@open-webui-valkey.ai.svc.cluster.local:6379/1'
        WEBUI_SECRET_KEY: "{{ .WEBUI_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: open-webui
