---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/litellm.home-operations.com/litellmvirtualkey_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMVirtualKey
metadata:
  name: open-webui
spec:
  keyAlias: open-webui
  models:
    - gpt-5.6-luna
    - gpt-5.6-terra
    - gpt-5.6-sol
    - qwen3-embedding
    - qwen3-4b-local
  proxyRef: litellm
  secretKey: key
  secretName: open-webui-litellm
