---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sparkyfitness
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sparkyfitness-secret
    template:
      data:
        BETTER_AUTH_SECRET: "{{ .BETTER_AUTH_SECRET }}"
        KANIDM_CLIENT_ID: "{{ .KANIDM_CLIENT_ID }}"
        KANIDM_CLIENT_SECRET: "{{ .KANIDM_CLIENT_SECRET }}"
        SPARKY_FITNESS_API_ENCRYPTION_KEY: "{{ .SPARKY_FITNESS_API_ENCRYPTION_KEY }}"
  dataFrom:
    - extract:
        key: sparkyfitness
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sparkyfitness-app-postgres
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sparkyfitness-app-postgres
    template:
      type: kubernetes.io/basic-auth
      data:
        username: sparkyfitness_app
        password: "{{ .POSTGRES_APP_PASSWORD }}"
  dataFrom:
    - extract:
        key: sparkyfitness
