---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lldap-external-secret
  namespace: system
spec:
  target:
    name: lldap-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        LLDAP_JWT_SECRET: "{{ .lldap_jwt_secret }}"
        LLDAP_LDAP_USER_PASS: "{{ .lldap_password }}"
        LLDAP_USER_DN: "{{ .lldap_user_dn }}"
        LLDAP_SERVER_KEY_SEED: "{{ .lldap_server_key_seed }}"
  data:
    - secretKey: lldap_user_dn
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 8f2e48fc-3e96-4d79-867a-b0490133afc0
        property: username
    - secretKey: lldap_password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 8f2e48fc-3e96-4d79-867a-b0490133afc0
        property: password
    - secretKey: lldap_jwt_secret
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 8f2e48fc-3e96-4d79-867a-b0490133afc0
        property: lldap_jwt_secret
    - secretKey: lldap_server_key_seed
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 8f2e48fc-3e96-4d79-867a-b0490133afc0
        property: lldap_server_key_seed
