---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lldap
  namespace: system
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controller:
      replicas: 1
      strategy: Recreate
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/lldap/lldap
      # TODO: Switch to release tag on next release
      tag: latest-alpine@sha256:5a10f409e9e8712732f9ad591ca82fd51280bd60e0551072781f5a075b4856c6

    env:
      LLDAP_HTTP_PORT: &port 80
      LLDAP_HTTP_URL: https://lldap.${SECRET_DOMAIN}
      LLDAP_LDAP_PORT: &ldapPort 389
      LLDAP_LDAP_BASE_DN: ${SECRET_AUTHELIA_BASE_DN}

    envFrom:
      - secretRef:
          name: lldap-secret

    service:
      main:
        ports:
          http:
            port: *port
          ldap:
            enabled: true
            port: *ldapPort

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress.${SECRET_DOMAIN}
          hajimari.io/icon: mdi:user-lock
          hajimari.io/enable: "true"
          hajimari.io/group: "authentication"
        hosts:
          - host: &host "lldap.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      data:
        enabled: true
        type: pvc
        existingClaim: lldap

    resources:
      requests:
        cpu: 5m
        memory: 128Mi
      limits:
        memory: 512Mi
