---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system
resources:
  - ./external-secret.yaml
  - ./pvc.yaml
  - ./helmrelease.yaml
  - ./gatus.yaml
commonLabels:
  app.kubernetes.io/name: lldap
  app.kubernetes.io/instance: lldap
